import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {decryptMarketingToken,metaGraphBase} from "@/lib/marketingMeta"
import {normalizeWhatsAppNumber,isValidWhatsAppNumber} from "@/lib/whatsappServer"
export const runtime="nodejs"
export async function POST(req){try{const user=await requireApiUser(req),r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,r.restaurantId,"marketing");const rid=r.restaurantId,b=await req.json();const {data:plugin}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",rid).eq("plugin_code","whatsapp-marketing").maybeSingle();if(plugin?.enabled!==true)throw new Error("WhatsApp Marketing plugin is not active");const {data:s}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",rid).eq("plugin_code","whatsapp-marketing").maybeSingle();const cfg=s?.config||{};if(cfg.allow_broadcasts===false)throw new Error("WhatsApp marketing broadcasts are disabled");const token=decryptMarketingToken(cfg.access_token),phone=cfg.phone_number_id;if(!token||!phone)throw new Error("Configure WhatsApp Marketing credentials first");const template=String(b.template_name||"").trim();if(!template)throw new Error("Approved WhatsApp template name is required");const {data:aud,error}=await supabaseCloudAdmin.from("marketing_audience_members").select("id,address").eq("restaurant_id",rid).eq("channel","whatsapp").eq("consent",true).is("unsubscribed_at",null).limit(100);if(error)throw error;const components=Array.isArray(b.components)?b.components:undefined;const results=[];for(const m of aud||[]){const recipient=normalizeWhatsAppNumber(m.address);if(!isValidWhatsAppNumber(recipient)){results.push({member_id:m.id,to:m.address,success:false,error:"Invalid international WhatsApp number"});continue}const idempotencyKey=b.post_id?`marketing:${String(b.post_id)}:${String(m.id)}`:null;if(idempotencyKey){const {data:existing}=await supabaseCloudAdmin.from("whatsapp_messages").select("wamid,status").eq("restaurant_id",rid).eq("idempotency_key",idempotencyKey).maybeSingle();if(existing?.wamid){results.push({member_id:m.id,to:m.address,success:true,id:existing.wamid,skipped:true});continue}}const payload={messaging_product:"whatsapp",to:recipient,type:"template",template:{name:template,language:{code:String(b.language||"en_US")}}};if(components)payload.template.components=components;const res=await fetch(`${metaGraphBase()}/${phone}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await res.json().catch(()=>({}));const ok=res.ok&&!d.error;const wamid=d.messages?.[0]?.id||null;results.push({member_id:m.id,to:recipient,success:ok,id:wamid,error:d.error?.message||null});if(ok){await supabaseCloudAdmin.from("whatsapp_messages").insert({restaurant_id:rid,direction:"outbound",recipient, message_type:"template",template_name:template,wamid,status:"accepted",payload,response:d,idempotency_key:idempotencyKey,marketing_post_id:b.post_id||null,campaign_id:b.campaign_id||null})}}const successful=results.filter(x=>x.success).length;
if(b.post_id){await supabaseCloudAdmin.from("marketing_posts").update({status:successful?"published":"failed",published_at:successful?new Date().toISOString():null,external_id:`whatsapp:${successful}`,error_message:successful?null:"WhatsApp send failed for all opted-in recipients",next_retry_at:null}).eq("id",String(b.post_id)).eq("restaurant_id",rid)}
await supabaseCloudAdmin.from("marketing_audit_logs").insert({restaurant_id:rid,actor_id:user.id,action:"whatsapp_marketing_send",platform:"whatsapp",entity_type:"template",metadata:{template,attempted:results.length,successful}});return NextResponse.json({success:Boolean(successful),results,error:successful?null:"WhatsApp send failed for all opted-in recipients"},{status:successful?200:400})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
