"use client"

import {useEffect,useState} from "react"
import {supabaseCloud} from "@/lib/supabaseCloud"

const card={background:"#fff",border:"1px solid #e4e9ef",borderRadius:16,padding:18,boxShadow:"0 8px 28px rgba(15,23,42,.05)"}
const input={width:"100%",padding:"10px 12px",border:"1px solid #d9e0e8",borderRadius:10,boxSizing:"border-box",background:"#fff"}
const btn={padding:"10px 14px",border:0,borderRadius:10,cursor:"pointer",fontWeight:700,background:"#153b2e",color:"#fff"}
export default function SupplierPortal(){
 const [user,setUser]=useState(null),[supplier,setSupplier]=useState(null),[rfqs,setRfqs]=useState([]),[items,setItems]=useState([]),[quotes,setQuotes]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({valid_until:"",delivery_days:"",payment_terms_days:"",notes:""}),[costs,setCosts]=useState({}),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 async function load(){setLoading(true);try{const {data:u}=await supabaseCloud.auth.getUser();if(!u?.user)throw Error("Please sign in with your supplier account");setUser(u.user);const {data:sp,error:se}=await supabaseCloud.from("supplier_portal_users").select("supplier_id,role,active").eq("user_id",u.user.id).eq("active",true).maybeSingle();if(se)throw se;if(!sp)throw Error("Supplier portal access is not assigned to this account");const {data:s}=await supabaseCloud.from("suppliers").select("*").eq("id",sp.supplier_id).maybeSingle();setSupplier(s);const {data:r,error:re}=await supabaseCloud.from("supplier_rfqs").select("*").in("status",["sent","quoted"]).order("response_due_at",{ascending:true});if(re)throw re;setRfqs(r||[]);const {data:q}=await supabaseCloud.from("supplier_rfq_quotes").select("*").eq("supplier_id",sp.supplier_id).order("created_at",{ascending:false});setQuotes(q||[])}catch(e){setMsg(e.message||"Unable to load portal")}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function open(rfq){setSelected(rfq);const {data,error}=await supabaseCloud.from("supplier_rfq_items").select("*").eq("rfq_id",rfq.id).order("created_at");if(error){setMsg(error.message);return}setItems(data||[]);const existing=quotes.find(q=>q.rfq_id===rfq.id);setForm({valid_until:existing?.valid_until||"",delivery_days:String(existing?.delivery_days||""),payment_terms_days:String(existing?.payment_terms_days||""),notes:existing?.notes||""});setCosts({})}
 async function submit(){if(!selected||!supplier)return;const quoteItems=items.map(x=>({rfq_item_id:x.id,unit_cost:Number(costs[x.id]||0),quantity:Number(x.quantity||1),tax_rate:0}));if(quoteItems.some(x=>x.unit_cost<=0)){setMsg("Enter a unit price for every RFQ item");return}setBusy(true);try{const {error}=await supabaseCloud.rpc("p1_10_submit_rfq_quote",{p_rfq_id:selected.id,p_supplier_id:supplier.id,p_items:quoteItems,p_valid_until:form.valid_until||null,p_delivery_days:Number(form.delivery_days||0),p_notes:form.notes||null});if(error)throw error;setMsg("Quote submitted successfully");await load();setSelected(null)}catch(e){setMsg(e.message||"Quote submission failed")}finally{setBusy(false)}}
 if(loading)return <main style={{padding:30}}>Loading Supplier Portal…</main>
 return <main style={{minHeight:"100vh",padding:"28px clamp(14px,4vw,50px) 50px",background:"#f6f8fb"}}><header style={{...card,marginBottom:14}}><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,opacity:.55}}>ANAIRA SUPPLIER PORTAL</div><h1 style={{margin:"6px 0"}}>{supplier?.name||supplier?.company_name||"Supplier"}</h1><p style={{margin:0,opacity:.65}}>Review RFQs, submit quotations and track your supplier relationship.</p></header>{msg&&<div style={{...card,marginBottom:14}}>{msg}</div>}<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,marginBottom:14}}><div style={card}><small>Open RFQs</small><strong style={{display:"block",fontSize:28,marginTop:5}}>{rfqs.length}</strong></div><div style={card}><small>Submitted Quotes</small><strong style={{display:"block",fontSize:28,marginTop:5}}>{quotes.length}</strong></div><div style={card}><small>Portal User</small><strong style={{display:"block",marginTop:5}}>{user?.email||"—"}</strong></div></section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14}}><div style={card}><h2 style={{marginTop:0}}>RFQs</h2>{rfqs.length?rfqs.map(x=><div key={x.id} style={{padding:"12px 0",borderBottom:"1px solid #eef1f4",display:"flex",justifyContent:"space-between",gap:10}}><div><b>{x.rfq_number}</b><div style={{opacity:.65}}>{x.title}</div><small>Due: {x.response_due_at?new Date(x.response_due_at).toLocaleString():"No deadline"}</small></div><button style={btn} onClick={()=>open(x)}>Open RFQ</button></div>):<p style={{opacity:.65}}>No RFQs assigned.</p>}</div>{selected&&<div style={card}><h2 style={{marginTop:0}}>Quote: {selected.rfq_number}</h2>{items.map(x=><label key={x.id} style={{display:"block",marginBottom:10}}><b>{x.name}</b><span style={{display:"block",fontSize:12,opacity:.6}}>Qty {x.quantity} {x.unit||""}</span><input style={input} type="number" min="0.01" step="0.01" placeholder="Your unit price" value={costs[x.id]||""} onChange={e=>setCosts({...costs,[x.id]:e.target.value})}/></label>)}<input style={input} type="date" value={form.valid_until} onChange={e=>setForm({...form,valid_until:e.target.value})} placeholder="Valid until"/><input style={input} type="number" min="0" placeholder="Delivery days" value={form.delivery_days} onChange={e=>setForm({...form,delivery_days:e.target.value})}/><input style={input} type="number" min="0" placeholder="Payment terms (days)" value={form.payment_terms_days} onChange={e=>setForm({...form,payment_terms_days:e.target.value})}/><textarea style={{...input,minHeight:80}} placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button style={btn} disabled={busy} onClick={submit}>Submit Quotation</button></div>}</section></main>
}
