import {NextResponse} from 'next/server'
import crypto from 'node:crypto'
import {supabaseCloudAdmin} from '@/lib/supabaseCloudServer'
import {requireApiUser} from '@/lib/serverAuth'
import {resolveRestaurantForUser} from '@/lib/restaurantResolver'
export const runtime='nodejs'
const hash=k=>crypto.createHash('sha256').update(String(k)).digest('hex')
const secret=()=>{const v=process.env.ANAIRA_SECRET_KEY||process.env.ANAIRA_SECRET;if(!v)throw new Error('ANAIRA_SECRET_KEY is required');return crypto.createHash('sha256').update(v).digest()}
const seal=v=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secret(),iv);const e=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),e.toString('base64')].join('.')}
async function ctx(req){const user=await requireApiUser(req);const r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw new Error('Restaurant profile not found');const {data:p,error}=await supabaseCloudAdmin.from('profiles').select('role').eq('id',user.id).maybeSingle();if(error)throw error;if(!['admin','super_admin'].includes(p?.role))throw new Error('Restaurant admin access required');return {restaurantId:r.restaurantId,role:p?.role}}
export async function GET(req){try{const {restaurantId}=await ctx(req);const {data,error}=await supabaseCloudAdmin.from('anaira_crm_connections').select('id,restaurant_id,crm_base_url,status,restaurant_api_key_last4,capabilities,last_sync_at,last_error,created_at,updated_at').eq('restaurant_id',restaurantId).maybeSingle();if(error)throw error;return NextResponse.json({ok:true,connection:data||null})}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400})}}
export async function POST(req){try{const {restaurantId,role}=await ctx(req);if(role!=='super_admin')throw new Error('Super Admin integration settings required');const b=await req.json();const action=String(b.action||'connect');if(action==='generate_key'){let apiKey='anr_'+crypto.randomBytes(30).toString('base64url');const {data,error}=await supabaseCloudAdmin.from('anaira_crm_connections').upsert({restaurant_id:restaurantId,restaurant_api_key_hash:hash(apiKey),restaurant_api_key_last4:apiKey.slice(-4),status:'disconnected',updated_at:new Date().toISOString()},{onConflict:'restaurant_id'}).select('id,restaurant_id,status,restaurant_api_key_last4').single();if(error)throw error;return NextResponse.json({ok:true,connection:data,generated_api_key:apiKey})}if(action==='disconnect'){await supabaseCloudAdmin.from('anaira_crm_connections').update({status:'disconnected',updated_at:new Date().toISOString()}).eq('restaurant_id',restaurantId);return NextResponse.json({ok:true,status:'disconnected'})}const crmBase=String(b.crm_base_url||'').trim().replace(/\/$/,'');const crmKey=String(b.crm_api_key||'').trim();if(!crmBase||!/^https?:\/\//i.test(crmBase))throw new Error('Valid CRM base URL is required');if(!crmKey)throw new Error('CRM API key is required');let apiKey=String(b.restaurant_api_key||'').trim();let generated=false;if(!apiKey){apiKey='anr_'+crypto.randomBytes(30).toString('base64url');generated=true}const row={restaurant_id:restaurantId,crm_base_url:crmBase,crm_api_key:seal(crmKey),restaurant_api_key_hash:hash(apiKey),restaurant_api_key_last4:apiKey.slice(-4),status:'connected',capabilities:b.capabilities||undefined,last_error:null,updated_at:new Date().toISOString()};const {data,error}=await supabaseCloudAdmin.from('anaira_crm_connections').upsert(row,{onConflict:'restaurant_id'}).select('id,restaurant_id,crm_base_url,status,restaurant_api_key_last4,capabilities,last_sync_at,last_error').single();if(error)throw error;return NextResponse.json({ok:true,connection:data,generated_api_key:generated?apiKey:null})}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400})}}
