import { requireFeature } from "@/lib/featureGateServer"
import { NextResponse } from "next/server"
import { supabaseCloudAdmin } from "@/lib/supabaseCloudServer"
import { requireApiUser } from "@/lib/serverAuth"
import { resolveRestaurantForUser } from "@/lib/restaurantResolver"
import { requireStaffPermission } from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
export async function GET(req){try{const u=await requireApiUser(req),r=await resolveRestaurantForUser(u);if(!r.restaurantId)throw new Error("Restaurant not found");await requireFeature(r.restaurantId, "p2-customer-display");await requireStaffPermission(u,r.restaurantId,"orders");const {data,error}=await supabaseCloudAdmin.from("p2_4_customer_displays").select("*").eq("restaurant_id",r.restaurantId).order("created_at");if(error)throw error;return NextResponse.json({success:true,displays:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:403})}}
export async function POST(req){try{const u=await requireApiUser(req),r=await resolveRestaurantForUser(u);if(!r.restaurantId)throw new Error("Restaurant not found");await requireFeature(r.restaurantId, "p2-customer-display");await requireStaffPermission(u,r.restaurantId,"orders");const b=await req.json();const action=String(b.action||"");if(action==="create"){const code=(String(b.display_code||crypto.randomUUID()).toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,12));const {data,error}=await supabaseCloudAdmin.from("p2_4_customer_displays").insert({restaurant_id:r.restaurantId,display_code:code,name:String(b.name||"Customer Display"),device_id:b.device_id||null,config:b.config||{},branding:b.branding||{}}).select().single();if(error)throw error;return NextResponse.json({success:true,display:data})}if(action==="update"){const id=String(b.id||"");const {data,error}=await supabaseCloudAdmin.from("p2_4_customer_displays").update({name:String(b.name||"Customer Display"),status:b.status||"offline",config:b.config||{},branding:b.branding||{},updated_at:new Date().toISOString()}).eq("id",id).eq("restaurant_id",r.restaurantId).select().single();if(error)throw error;return NextResponse.json({success:true,display:data})}throw new Error("Unsupported action")}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
