-- Reproduce the production Restaurant Core order/billing RLS alignment.
DROP POLICY IF EXISTS orders_insert_staff_permission ON public.orders;
CREATE POLICY orders_insert_staff_permission ON public.orders FOR INSERT TO authenticated WITH CHECK (is_staff_or_admin() AND is_restaurant_member(restaurant_id) AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders')));
DROP POLICY IF EXISTS order_items_insert_staff_permission ON public.order_items;
CREATE POLICY order_items_insert_staff_permission ON public.order_items FOR INSERT TO authenticated WITH CHECK (is_staff_or_admin() AND EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_items.order_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders'))));
DROP POLICY IF EXISTS order_items_update_staff_permission ON public.order_items;
CREATE POLICY order_items_update_staff_permission ON public.order_items FOR UPDATE TO authenticated USING (is_staff_or_admin() AND EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_items.order_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders')))) WITH CHECK (is_staff_or_admin() AND EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_items.order_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders'))));
DROP POLICY IF EXISTS order_item_modifiers_staff_permission ON public.order_item_modifiers;
CREATE POLICY order_item_modifiers_staff_permission ON public.order_item_modifiers FOR ALL TO authenticated USING (is_staff_or_admin() AND EXISTS (SELECT 1 FROM public.order_items oi JOIN public.orders o ON o.id = oi.order_id WHERE oi.id = order_item_modifiers.order_item_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders')))) WITH CHECK (is_staff_or_admin() AND EXISTS (SELECT 1 FROM public.order_items oi JOIN public.orders o ON o.id = oi.order_id WHERE oi.id = order_item_modifiers.order_item_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders'))));
DROP POLICY IF EXISTS orders_select_staff_permission ON public.orders;
CREATE POLICY orders_select_staff_permission ON public.orders FOR SELECT TO authenticated USING (is_super_admin() OR (is_staff_or_admin() AND restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders'))));
DROP POLICY IF EXISTS order_items_select_staff_permission ON public.order_items;
CREATE POLICY order_items_select_staff_permission ON public.order_items FOR SELECT TO authenticated USING (is_super_admin() OR EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_items.order_id AND o.restaurant_id = current_restaurant_id() AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'orders')) AND is_staff_or_admin()));
DROP POLICY IF EXISTS order_payments_select_staff_permission ON public.order_payments;
CREATE POLICY order_payments_select_staff_permission ON public.order_payments FOR SELECT TO authenticated USING (is_super_admin() OR (is_staff_or_admin() AND is_restaurant_member(restaurant_id) AND (current_user_role() = 'admin' OR has_staff_permission(auth.uid(), 'billing'))));
