"use client"

import { indiaDateKey } from "@/lib/indiaTime"
import { useCallback, useEffect, useState } from "react"
import { supabasePublic as supabase } from "@/lib/supabasePublic"

const tabs=[
 ["payments","💳","Payments"],["channels","🌐","Channels"],["website","🖥️","Website"],["brands","🍱","Virtual Brands"],
 ["terminals","🧾","Terminals / Offline"],["staff","👨‍💼","Staff / Approvals"],["menu","📢","Menu Publishing"],["integrations","🔗","Integrations"]
]
const Card=({title,children})=><section className="ccard"><h2>{title}</h2>{children}</section>

export default function CompleteSuite(){
 const [rid,setRid]=useState(""); const [tab,setTab]=useState("payments"); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState(""); const [d,setD]=useState({}); const [paymentPluginEnabled,setPaymentPluginEnabled]=useState(false);
 const [web,setWeb]=useState({slug:"",domain:"",enabled:false,seo_title:"",seo_description:"",whatsapp_number:""});
 const [pay,setPay]=useState({provider:"payment-accounts",display_name:"Merchant Payments & Voice",merchant_reference:"",active:false,merchant_name:"",upi_id:"",auto_payment_detection:false,voice_enabled:true,voice_language:"hi-IN"});
 const [brand,setBrand]=useState({name:"",code:"",active:true});
 const [shift,setShift]=useState({staff_id:"",shift_date:indiaDateKey(),start_at:"",end_at:"",break_minutes:0});
 const [approval,setApproval]=useState({request_type:"discount",reason:"",payload:"{}"});
 const getRid=useCallback(async()=>{const {data:u}=await supabase.auth.getUser();if(!u?.user)throw new Error("Please sign in again.");const {data,error}=await supabase.from("profiles").select("restaurant_id").eq("id",u.user.id).maybeSingle();if(error)throw error;if(!data?.restaurant_id)throw new Error("No restaurant linked with this account.");return data.restaurant_id},[]);
 const load=useCallback(async()=>{try{setLoading(true);const r=rid||await getRid();setRid(r);const q=await Promise.all([
  supabase.from("restaurant_channels").select("*").eq("restaurant_id",r).order("display_name"),
  supabase.from("restaurant_terminals").select("*").eq("restaurant_id",r).order("terminal_name"),
  supabase.from("restaurant_integrations").select("*").eq("restaurant_id",r).order("display_name"),
  supabase.from("restaurant_virtual_brands").select("*").eq("restaurant_id",r).order("name"),
  supabase.from("restaurant_website_settings").select("*").eq("restaurant_id",r).maybeSingle(),
  supabase.from("restaurant_staff_shifts").select("*").eq("restaurant_id",r).order("shift_date",{ascending:false}).limit(30),
  supabase.from("restaurant_approval_requests").select("*").eq("restaurant_id",r).order("created_at",{ascending:false}).limit(30),
  supabase.from("restaurant_menu_publications").select("*").eq("restaurant_id",r).order("created_at",{ascending:false}).limit(30),
  supabase.from("restaurant_offline_queue").select("*").eq("restaurant_id",r).order("queued_at",{ascending:false}).limit(30),
  supabase.from("restaurant_plugins").select("plugin_code,enabled").eq("restaurant_id",r).in("plugin_code",["payment-accounts"]),
  supabase.from("restaurant_payment_accounts").select("*").eq("restaurant_id",r).eq("provider","payment-accounts").order("updated_at",{ascending:false}).limit(1)
 ]);const pluginEnabled=Boolean(q[9].data?.some(x=>x.enabled===true));setPaymentPluginEnabled(pluginEnabled);setD({channels:q[0].data||[],terminals:q[1].data||[],integrations:q[2].data||[],brands:q[3].data||[],website:q[4].data,shifts:q[5].data||[],approvals:q[6].data||[],publications:q[7].data||[],offline:q[8].data||[]});if(q[4].data)setWeb(x=>({...x,...q[4].data}));const account=q[10].data?.[0];if(account){const cfg=account.settings||{};setPay(x=>({...x,provider:account.provider||x.provider,display_name:account.display_name||x.display_name,merchant_reference:account.merchant_reference||"",active:account.active===true,merchant_name:cfg.merchant_name||"",upi_id:cfg.upi_id||"",auto_payment_detection:cfg.auto_payment_detection===true,voice_enabled:cfg.voice_enabled!==false,voice_language:cfg.voice_language||"hi-IN"}));}if(!pluginEnabled&&tab==="payments")setTab("channels");}catch(e){setMsg(e?.message||"Unable to load") }finally{setLoading(false)}},[getRid,rid]);
 useEffect(()=>{load()},[load]);
 async function save(table,row,conflict,success){const {error}=await supabase.from(table).upsert(row,{onConflict:conflict});setMsg(error?.message||success);if(!error)load()}
 if(loading)return <main className="complete"><div className="loading">Loading completion hub…</div></main>
 return <main className="complete">
  <header className="hero"><div><small>FINAL NON-INVENTORY COMPLETION</small><h1>Restaurant Suite Control</h1><p>Remaining Anaira operations in one theme-based control hub.</p></div><button onClick={load}>↻ Refresh</button></header>
  <nav className="tabs">{tabs.filter(([id])=>id!=="payments"||paymentPluginEnabled).map(([id,i,n])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}>{i} {n}</button>)}</nav>
  {msg&&<div className="msg">{msg}</div>}
  {tab==="payments"&&paymentPluginEnabled&&<div className="grid"><Card title="Merchant Payment Account"><form onSubmit={e=>{e.preventDefault();const settings={merchant_name:pay.merchant_name,upi_id:pay.upi_id,auto_payment_detection:pay.auto_payment_detection,voice_enabled:pay.voice_enabled,voice_language:pay.voice_language};save("restaurant_payment_accounts",{restaurant_id:rid,provider:pay.provider,display_name:pay.display_name,merchant_reference:pay.merchant_reference,active:pay.active,settings,updated_at:new Date().toISOString()},"restaurant_id,provider,display_name","Merchant payment settings saved")}}><input placeholder="Merchant / Restaurant name" value={pay.merchant_name} onChange={e=>setPay({...pay,merchant_name:e.target.value})}/><input placeholder="Merchant UPI ID (e.g. restaurant@upi)" value={pay.upi_id} onChange={e=>setPay({...pay,upi_id:e.target.value})}/><input placeholder="Merchant reference" value={pay.merchant_reference} onChange={e=>setPay({...pay,merchant_reference:e.target.value})}/><input placeholder="Provider" value={pay.provider} onChange={e=>setPay({...pay,provider:e.target.value})}/><label><input type="checkbox" checked={pay.active} onChange={e=>setPay({...pay,active:e.target.checked})}/> Account active</label><label><input type="checkbox" checked={pay.auto_payment_detection} onChange={e=>setPay({...pay,auto_payment_detection:e.target.checked})}/> Auto payment detection</label><label><input type="checkbox" checked={pay.voice_enabled} onChange={e=>setPay({...pay,voice_enabled:e.target.checked})}/> Voice payment announcement</label><select value={pay.voice_language} onChange={e=>setPay({...pay,voice_language:e.target.value})}><option value="hi-IN">Hindi</option><option value="en-IN">English (India)</option></select><button>Save Payment Settings</button></form><p className="muted">Super Admin controls this module from Plugins → Merchant Payments & Voice. Automatic payment confirmation still requires a merchant provider webhook/API.</p></Card><Card title="Supported payment workflows"><ul><li>UPI / QR</li><li>GPay / PhonePe customer payment</li><li>Receipt / UTR attachment</li><li>Automatic verified payment status via provider webhook</li><li>Voice announcement on POS device</li><li>Cash / card / split payment records</li></ul></Card></div>}
  {tab==="channels"&&<Card title="Unified order channel hub"><div className="list">{d.channels.map(x=><div className="row" key={x.id}><b>{x.display_name}</b><span>{x.active?"Active":"Disabled"}</span><button onClick={async()=>{const {error}=await supabase.from("restaurant_channels").update({active:!x.active,updated_at:new Date().toISOString()}).eq("id",x.id).eq("restaurant_id",rid);setMsg(error?.message||"Channel updated");if(!error)load()}}>{x.active?"Disable":"Enable"}</button></div>)}</div></Card>}
  {tab==="website"&&<Card title="Restaurant website / direct ordering"><form onSubmit={e=>{e.preventDefault();save("restaurant_website_settings",{restaurant_id:rid,...web,updated_at:new Date().toISOString()},"restaurant_id","Website settings saved")}}><input placeholder="Slug" value={web.slug} onChange={e=>setWeb({...web,slug:e.target.value})}/><input placeholder="Custom domain" value={web.domain} onChange={e=>setWeb({...web,domain:e.target.value})}/><input placeholder="SEO title" value={web.seo_title} onChange={e=>setWeb({...web,seo_title:e.target.value})}/><textarea placeholder="SEO description" value={web.seo_description} onChange={e=>setWeb({...web,seo_description:e.target.value})}/><input placeholder="WhatsApp number" value={web.whatsapp_number} onChange={e=>setWeb({...web,whatsapp_number:e.target.value})}/><label><input type="checkbox" checked={web.enabled} onChange={e=>setWeb({...web,enabled:e.target.checked})}/> Enabled</label><button>Save website</button></form></Card>}
  {tab==="brands"&&<div className="grid"><Card title="Create virtual brand"><form onSubmit={e=>{e.preventDefault();save("restaurant_virtual_brands",{restaurant_id:rid,...brand,updated_at:new Date().toISOString()},"restaurant_id,code","Virtual brand saved");setBrand({name:"",code:"",active:true})}}><input required placeholder="Brand name" value={brand.name} onChange={e=>setBrand({...brand,name:e.target.value})}/><input required placeholder="Brand code" value={brand.code} onChange={e=>setBrand({...brand,code:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/><label><input type="checkbox" checked={brand.active} onChange={e=>setBrand({...brand,active:e.target.checked})}/> Active</label><button>Save brand</button></form></Card><Card title="Brands"><div className="list">{d.brands.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.code} • {x.active?"Active":"Disabled"}</span></div>)}</div></Card></div>}
  {tab==="terminals"&&<div className="grid"><Card title="POS terminals"><div className="list">{d.terminals.map(x=><div className="row" key={x.id}><b>{x.terminal_name}</b><span>{x.device_type} • {x.offline_enabled?"Offline ready":"Online only"}</span></div>)}</div></Card><Card title="Offline queue"><button onClick={async()=>{const {error}=await supabase.from("restaurant_offline_queue").insert({restaurant_id:rid,operation_type:"sync_test",local_reference:`local-${Date.now()}`,payload:{source:"complete-hub"}});setMsg(error?.message||"Offline queue item created");if(!error)load()}}>Create sync test</button><div className="list">{d.offline.map(x=><div className="row" key={x.id}><b>{x.operation_type}</b><span>{x.status} • {x.attempts} attempts</span></div>)}</div></Card></div>}
  {tab==="staff"&&<div className="grid"><Card title="Staff shift scheduler"><form onSubmit={async e=>{e.preventDefault();const {error}=await supabase.from("restaurant_staff_shifts").insert({restaurant_id:rid,...shift});setMsg(error?.message||"Shift saved");if(!error)load()}}><input placeholder="Staff UUID" value={shift.staff_id} onChange={e=>setShift({...shift,staff_id:e.target.value})}/><input type="date" value={shift.shift_date} onChange={e=>setShift({...shift,shift_date:e.target.value})}/><input type="datetime-local" value={shift.start_at} onChange={e=>setShift({...shift,start_at:e.target.value})}/><input type="datetime-local" value={shift.end_at} onChange={e=>setShift({...shift,end_at:e.target.value})}/><input type="number" placeholder="Break minutes" value={shift.break_minutes} onChange={e=>setShift({...shift,break_minutes:e.target.value})}/><button>Save shift</button></form><div className="list">{d.shifts.slice(0,10).map(x=><div className="row" key={x.id}><b>{x.staff_id.slice(0,8)}</b><span>{x.shift_date} • {x.status}</span></div>)}</div></Card><Card title="Manager approvals"><form onSubmit={async e=>{e.preventDefault();let payload={};try{payload=JSON.parse(approval.payload||"{}")}catch{setMsg("Payload must be valid JSON");return}const {error}=await supabase.from("restaurant_approval_requests").insert({restaurant_id:rid,request_type:approval.request_type,reason:approval.reason,payload});setMsg(error?.message||"Approval request created");if(!error)load()}}><select value={approval.request_type} onChange={e=>setApproval({...approval,request_type:e.target.value})}><option>discount</option><option>refund</option><option>void</option><option>price_override</option><option>complimentary</option></select><input placeholder="Reason" value={approval.reason} onChange={e=>setApproval({...approval,reason:e.target.value})}/><textarea placeholder="Payload JSON" value={approval.payload} onChange={e=>setApproval({...approval,payload:e.target.value})}/><button>Create approval</button></form><div className="list">{d.approvals.slice(0,10).map(x=><div className="row" key={x.id}><b>{x.request_type}</b><span>{x.status} • {x.reason||"No reason"}</span></div>)}</div></Card></div>}
  {tab==="menu"&&<Card title="Central menu publishing"><p className="muted">Version and publish digital menu configuration without touching inventory.</p><div className="publish">{["website","qr","kiosk","zomato","swiggy"].map(c=><button key={c} onClick={async()=>{const n=d.publications.filter(x=>x.channel_code===c).length+1;const {error}=await supabase.from("restaurant_menu_publications").insert({restaurant_id:rid,channel_code:c,version:n,status:"published",published_at:new Date().toISOString(),payload:{source:"central-menu"}});setMsg(error?.message||`${c} menu published`);if(!error)load()}}>Publish {c}</button>)}</div><div className="list">{d.publications.map(x=><div className="row" key={x.id}><b>{x.channel_code}</b><span>v{x.version} • {x.status}</span></div>)}</div></Card>}
  {tab==="integrations"&&<Card title="Accounting, messaging & delivery integrations"><div className="list">{d.integrations.map(x=><div className="row" key={x.id}><div><b>{x.display_name}</b><small>{x.integration_type} / {x.provider}</small></div><button onClick={async()=>{const {error}=await supabase.from("restaurant_integrations").update({active:!x.active,updated_at:new Date().toISOString()}).eq("id",x.id).eq("restaurant_id",rid);setMsg(error?.message||"Integration updated");if(!error)load()}}>{x.active?"Disable":"Enable"}</button></div>)}</div><p className="muted">Credentials should be connected through secured server-side provider configuration; this registry does not expose secrets in the browser.</p></Card>}
  <style jsx global>{`.complete{min-height:100vh;padding:24px;max-width:1450px;margin:auto;background:var(--background,var(--background));color:var(--text,var(--text))}.hero{display:flex;justify-content:space-between;gap:20px;padding:28px;border:1px solid var(--border,rgba(255,255,255,.12));border-radius:24px;background:var(--surface,var(--surface-2))}.hero small{color:var(--primary,#e5ad38);font-weight:800;letter-spacing:.16em}.hero h1{margin:8px 0;font:800 clamp(28px,4vw,48px)/1.05 Georgia,serif}.hero p,.muted,.row span,.row small{color:var(--muted,var(--muted))}.hero button,.tabs button,.ccard button{border:1px solid var(--border,rgba(255,255,255,.12));border-radius:11px;padding:10px 14px;background:var(--surface-2,var(--surface-2));color:var(--text,var(--text));font-weight:700;cursor:pointer}.tabs{display:flex;gap:8px;overflow:auto;padding:16px 0}.tabs button{white-space:nowrap}.tabs .active,.hero button:hover,.ccard button:hover{background:var(--primary,#e5ad38);color:#111}.msg{margin-bottom:16px;padding:12px;border:1px solid rgba(229,173,56,.3);border-radius:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.ccard{padding:20px;border:1px solid var(--border,rgba(255,255,255,.12));border-radius:20px;background:var(--surface,var(--surface-2))}.ccard h2{margin:0 0 16px;font-size:21px}.ccard form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ccard input,.ccard select,.ccard textarea{width:100%;padding:11px;border:1px solid var(--border,rgba(255,255,255,.12));border-radius:10px;background:rgba(0,0,0,.15);color:var(--text,var(--text))}.ccard textarea{grid-column:1/-1;min-height:90px}.ccard form button{grid-column:1/-1}.list{display:flex;flex-direction:column}.row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 0;border-top:1px solid rgba(255,255,255,.07)}.row small{display:block}.publish{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:18px}.loading{min-height:70vh;display:grid;place-items:center;color:var(--muted,var(--muted))}@media(max-width:850px){.grid{grid-template-columns:1fr}.publish{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.complete{padding:14px}.hero{flex-direction:column}.ccard form{grid-template-columns:1fr}.publish{grid-template-columns:1fr}}`}</style>
 </main>
}
