import {NextResponse} from "next/server"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission,requireSuperAdmin} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {signOAuthState} from "@/lib/marketingMeta"
import {getMetaServerConfig} from "@/lib/marketingConfig"
export const runtime="nodejs"
export async function GET(req){try{const user=await requireApiUser(req);const r=await resolveRestaurantForUser(user);const u=new URL(req.url);const platform=String(u.searchParams.get("platform")||"").toLowerCase();const scope=String(u.searchParams.get("scope")||"restaurant").toLowerCase();if(!["facebook","instagram"].includes(platform))throw new Error("Unsupported Meta platform");if(!["platform","restaurant"].includes(scope))throw new Error("Invalid Meta OAuth scope");if(scope==="platform"){await requireSuperAdmin(user)}else{if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,r.restaurantId,"marketing");const code=`${platform}-integration`;const {data:plugin}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",r.restaurantId).eq("plugin_code",code).maybeSingle();if(plugin?.enabled!==true)throw new Error(`${platform} plugin is not active for this restaurant`)}const cfg=await getMetaServerConfig();const appId=cfg.appId,redirectUri=cfg.redirectUri||new URL("/api/marketing/meta/oauth/callback",req.url).toString();if(!appId||!cfg.appSecret)throw new Error("Meta OAuth is not configured. Open Marketing → Settings and save the Meta App credentials.");const scopes=cfg.scopes;const state=signOAuthState({userId:user.id,restaurantId:scope==="platform"?null:r.restaurantId,platform,scope});const url=new URL(`https://www.facebook.com/${cfg.graphVersion}/dialog/oauth`);url.searchParams.set("client_id",appId);url.searchParams.set("redirect_uri",redirectUri);url.searchParams.set("response_type","code");url.searchParams.set("scope",scopes);url.searchParams.set("state",state);return NextResponse.json({success:true,url:url.toString()})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
