"use client"
import Link from "next/link"

const tiers=[
 {code:"P0",title:"Core POS",items:["POS & Orders","Tables","Kitchen / KDS","Billing","Inventory","Production","Delivery","Customers","Procurement","Payments","Printing","QR & Ordering","Reservations","Reports"],note:"P0 is the core product. These modules are not treated as P1/P2 add-ons."},
 {code:"P1",title:"Advanced Operations",items:["Restaurant Suite","Enterprise HQ","Payment Terminals","Payment Reconciliation","Supplier Automation","Marketing Hub","Advanced Reporting"],note:"P1 activation is controlled per restaurant in Plugin Control Center."},
 {code:"P2",title:"Advanced Operations",items:["Call Center","Banquet / Events / Catering","Advanced Kiosk","Customer Display","Device HQ","AI Decision Intelligence"],note:"P2 activation is controlled per restaurant in Plugin Control Center."},
]
export default function PlatformControlCenter(){return <main style={{minHeight:"100vh",padding:"32px",background:"var(--background)",color:"var(--text)"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>SUPERADMIN</div><h1 style={{margin:"8px 0 10px"}}>Platform Control Center</h1><p style={{color:"var(--muted)",lineHeight:1.6}}>P0 is core. P1 and P2 are restaurant-level controlled feature tiers. Open Plugin Control Center to activate or deactivate the exact P1/P2 modules for a selected restaurant.</p><div style={{display:"grid",gap:16,marginTop:22}}>{tiers.map(t=><section key={t.code} style={{padding:22,borderRadius:18,border:"1px solid var(--border)",background:"var(--surface)"}}><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"center"}}><div><div style={{fontSize:11,fontWeight:900,color:"var(--muted)",letterSpacing:".1em"}}>{t.code}</div><h2 style={{margin:"5px 0"}}>{t.title}</h2></div><span style={{fontSize:24}}>{t.code==="P0"?"🧾":t.code==="P1"?"⚙️":"🚀"}</span></div><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:12}}>{t.items.map(x=><span key={x} style={{padding:"8px 11px",borderRadius:10,border:"1px solid var(--border)",fontSize:12,fontWeight:700}}>{x}</span>)}</div><p style={{margin:"14px 0 0",color:"var(--muted)",fontSize:13}}>{t.note}</p></section>)}</div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:24}}><Link href="/super-admin/plugins" style={{padding:"12px 16px",borderRadius:12,background:"var(--primary)",color:"#111",fontWeight:900,textDecoration:"none"}}>🧩 Open Plugin Control Center — P1 / P2 Activate / Deactivate</Link><Link href="/super-admin" style={{padding:"12px 16px",borderRadius:12,border:"1px solid var(--border)",color:"var(--text)",fontWeight:800,textDecoration:"none"}}>← SuperAdmin Dashboard</Link></div></div></main>}
