"use client"
import { useEffect, useState } from "react"

const modules = [
 ["channels","🌐","Channels","Order channels and availability","/dashboard/restaurant-suite/complete?tab=channels"],
 ["website","🖥️","Website","Direct ordering, domain and SEO","/dashboard/restaurant-suite/complete?tab=website"],
 ["virtual_brands","🍱","Virtual Brands","Multi-brand restaurant setup","/dashboard/restaurant-suite/complete?tab=brands"],
 ["terminals","🧾","POS Terminals","Registered POS devices","/dashboard/restaurant-suite/complete?tab=terminals"],
 ["staff","👨‍💼","Staff / Approvals","Shifts and manager approvals","/dashboard/restaurant-suite/complete?tab=staff"],
 ["menu","📢","Menu Publishing","Central website, QR, kiosk and aggregator menu versions","/dashboard/restaurant-suite/complete?tab=menu"],
 ["integrations","🔗","Integrations","Accounting, messaging and delivery adapters","/dashboard/restaurant-suite/complete?tab=integrations"],
]
export default function UnifiedRestaurantSuite(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/restaurant-suite/summary",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load");setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const m=data?.modules||{}
 return <main className="us"><header><div><small>ANAIRA • P0.6</small><h1>Unified Restaurant Suite</h1><p>One control layer for Channels, Website, Virtual Brands, POS Terminals, Staff, Menu Publishing and Integrations. Payment QR / Merchant Payments remains a separate module.</p></div><button onClick={load}>↻ Refresh</button></header>
  {error&&<div className="error">{error}</div>}
  {loading?<div className="loading">Loading Suite control…</div>:<>
   <section className="kpis"><K label="Active Channels" value={`${m.channels?.active||0}/${m.channels?.total||0}`}/><K label="Virtual Brands" value={`${m.virtual_brands?.active||0}`}/><K label="POS Terminals" value={m.terminals?.total||0}/><K label="Pending Approvals" value={m.staff?.pending_approvals||0}/><K label="Menu Publications" value={m.menu?.publications||0}/><K label="Active Integrations" value={`${m.integrations?.active||0}/${m.integrations?.total||0}`}/></section>
   <section className="grid">{modules.map(([id,icon,title,desc,href])=><a className="card" href={href} key={id}><span className="icon">{icon}</span><div><h2>{title}</h2><p>{desc}</p><strong>{status(id,m)}</strong></div><span className="arrow">→</span></a>)}</section>
   <section className="bottom"><div className="panel"><h2>Menu publishing status</h2><p>{m.menu?.latest?`Latest: ${m.menu.latest.channel_code} • v${m.menu.latest.version} • ${m.menu.latest.status}`:"No menu publication recorded yet."}</p><a href="/dashboard/restaurant-suite/complete?tab=menu">Open Menu Publishing →</a></div><div className="panel separate"><h2>Payment QR / Merchant Payments</h2><p>Payment accounts, QR configuration and reconciliation are intentionally outside Restaurant Suite.</p><a href="/dashboard/payment-qr">Open Payment QR →</a><a href="/dashboard/payment-reconciliation">Open Reconciliation →</a></div></section>
  </>}
  <style jsx>{`.us{min-height:100vh;max-width:1450px;margin:auto;padding:24px;color:var(--text);background:var(--background)}header{display:flex;justify-content:space-between;gap:20px;padding:28px;border:1px solid var(--border);border-radius:24px;background:var(--surface)}header small{color:var(--primary);font-weight:800;letter-spacing:.16em}h1{margin:8px 0;font:800 clamp(30px,4vw,50px)/1.05 Georgia,serif}header p{max-width:850px;color:var(--muted);line-height:1.6}button,a{font:inherit}header button{height:42px;padding:0 15px;border:1px solid var(--border);border-radius:11px;background:var(--surface-2);color:var(--text);font-weight:800;cursor:pointer}.error{margin-top:14px;padding:12px;border-radius:12px;border:1px solid rgba(220,80,80,.4)}.loading{min-height:40vh;display:grid;place-items:center;color:var(--muted)}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:18px 0}.kpi,.card,.panel{border:1px solid var(--border);border-radius:18px;background:var(--surface)}.kpi{padding:18px}.kpi small{color:var(--muted);display:block}.kpi strong{display:block;margin-top:7px;font-size:25px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{display:flex;align-items:center;gap:13px;padding:18px;text-decoration:none;color:var(--text);min-height:130px}.card:hover{border-color:var(--primary);transform:translateY(-1px)}.icon{width:44px;height:44px;display:grid;place-items:center;border-radius:13px;background:rgba(229,173,56,.10);flex:0 0 auto;font-size:22px}.card div{flex:1;min-width:0}.card h2{margin:0 0 6px;font-size:18px}.card p,.panel p{margin:0 0 10px;color:var(--muted);font-size:12px;line-height:1.45}.card strong{font-size:11px;color:var(--primary);text-transform:uppercase}.arrow{font-size:22px;color:var(--primary)}.bottom{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.panel{padding:20px}.panel h2{margin:0 0 9px;font-size:18px}.panel a{display:inline-block;margin-right:12px;color:var(--primary);font-weight:800;text-decoration:none}.separate{border-color:rgba(229,173,56,.35)}@media(max-width:1100px){.kpis{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.us{padding:14px}header{flex-direction:column}.kpis,.grid,.bottom{grid-template-columns:1fr}.card{min-height:105px}}`}</style>
 </main>
}
function K({label,value}){return <div className="kpi"><small>{label}</small><strong>{value}</strong></div>}
function status(id,m){if(id==="channels")return `${m.channels?.active||0} active`;if(id==="website")return m.website?.configured?"configured":"configure website";if(id==="virtual_brands")return `${m.virtual_brands?.active||0} active`;if(id==="terminals")return `${m.terminals?.total||0} registered`;if(id==="staff")return `${m.staff?.pending_approvals||0} pending`;if(id==="menu")return `${m.menu?.publications||0} publications`;return `${m.integrations?.active||0} active`}
