import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
import {decryptMarketingToken,isMarketingTokenExpired,metaGraphBase} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
export async function GET(req){try{await sa(req);const {data,error}=await supabaseCloudAdmin.from("platform_marketing_connections").select("id,platform,account_id,account_name,profile_image_url,status,metadata,connected_at,updated_at,token_expires_at,last_tested_at,last_test_status,last_test_error").order("updated_at",{ascending:false});if(error)throw error;return NextResponse.json({success:true,connections:(data||[]).map(x=>({...x,computed_status:isMarketingTokenExpired(x.token_expires_at)?"expired":x.status}))})}catch(e){return NextResponse.json({success:false,error:e.message},{status:403})}}
export async function POST(req){try{const u=await sa(req);const platform=String(new URL(req.url).searchParams.get("platform")||"").toLowerCase();if(!["facebook","instagram"].includes(platform))throw new Error("Connection test is available for Facebook and Instagram");const {data:c,error}=await supabaseCloudAdmin.from("platform_marketing_connections").select("id,account_id,encrypted_access_token,token_expires_at").eq("platform",platform).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!c?.encrypted_access_token)throw new Error(`${platform} is not connected`);if(isMarketingTokenExpired(c.token_expires_at))throw new Error("Meta token is expired or expiring. Reconnect the account.");const token=decryptMarketingToken(c.encrypted_access_token);const fields=platform==="facebook"?"id,name":"id,username,name,profile_picture_url";const r=await fetch(`${metaGraphBase()}/${c.account_id}?fields=${encodeURIComponent(fields)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));const ok=r.ok&&!d.error;await supabaseCloudAdmin.from("platform_marketing_connections").update({last_tested_at:new Date().toISOString(),last_test_status:ok?"success":"failed",last_test_error:ok?null:(d.error?.message||`Meta API ${r.status}`),status:ok?"connected":"error"}).eq("id",c.id);await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"meta_connection_test",platform,entity_type:"connection",entity_id:c.id,metadata:{success:ok}});if(!ok)throw new Error(d.error?.message||"Meta connection test failed");return NextResponse.json({success:true,message:"Connection test passed",account:d})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function DELETE(req){try{const u=await sa(req);const platform=String(new URL(req.url).searchParams.get("platform")||"").toLowerCase();if(!["facebook","instagram","whatsapp"].includes(platform))throw new Error("Unsupported platform");const {data,error}=await supabaseCloudAdmin.from("platform_marketing_connections").update({status:"disconnected",encrypted_access_token:null,token_expires_at:null,last_test_status:null,last_test_error:null,metadata:{disconnected_at:new Date().toISOString(),disconnected_by:u.id}}).eq("platform",platform).select("id");if(error)throw error;await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"marketing_disconnect",platform,entity_type:"connection",metadata:{count:data?.length||0}});return NextResponse.json({success:true,count:data?.length||0})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
