"use client"
import {useEffect,useState} from "react"
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`
export default function GiftCards(){
 const [cards,setCards]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[tab,setTab]=useState("cards"),[form,setForm]=useState({code:"",amount:"",purchaser_name:"",recipient_name:"",recipient_phone:"",expires_at:""}),[redeem,setRedeem]=useState({code:"",amount:"",notes:""}),[lookup,setLookup]=useState(null)
 async function load(){setLoading(true);try{const r=await fetch(`/api/gift-cards${q?`?q=${encodeURIComponent(q)}`:""}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setCards(d.gift_cards||[])}catch(e){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function act(operation,payload){setMsg("");try{const r=await fetch("/api/gift-cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation,...payload,idempotency_key:crypto.randomUUID()})});const d=await r.json();if(!r.ok||d.success===false)throw new Error(d.error||"Operation failed");setMsg(operation+" successful");await load();return d}catch(e){setMsg(e.message);throw e}}
 async function submit(e){e.preventDefault();await act("issue",form);setForm({code:"",amount:"",purchaser_name:"",recipient_name:"",recipient_phone:"",expires_at:""})}
 async function doRedeem(e){e.preventDefault();await act("redeem",redeem);setRedeem({code:"",amount:"",notes:""})}
 return <main className="gc"><header><div><span>P1.1 • GIFT CARDS</span><h1>Gift Cards</h1><p>Create, sell, activate, redeem and audit gift cards.</p></div><button onClick={load}>↻ Refresh</button></header>
 <nav><button className={tab==="cards"?"active":""} onClick={()=>setTab("cards")}>Cards & Ledger</button><button className={tab==="sell"?"active":""} onClick={()=>setTab("sell")}>Sell / Issue</button><button className={tab==="redeem"?"active":""} onClick={()=>setTab("redeem")}>Redeem</button><button className={tab==="lookup"?"active":""} onClick={()=>setTab("lookup")}>QR / Code Lookup</button></nav>
 {msg&&<div className="msg">{msg}</div>}
 {tab==="cards"&&<section><div className="toolbar"><input placeholder="Search gift card code…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>Search</button></div><div className="grid">{loading?<p>Loading…</p>:cards.map(c=><article key={c.id}><div className="row"><b>{c.code}</b><strong>{money(c.balance)}</strong></div><small>{c.status} • Initial {money(c.initial_balance)}{c.expires_at ? ` • Expires ${new Date(c.expires_at).toLocaleDateString("en-IN")}` : ""}</small><div className="ledger">{(c.gift_card_transactions||[]).map(t=><div key={t.id}><span>{t.transaction_type}</span><span>{money(t.amount)} → {money(t.balance_after)}</span></div>)}</div><button onClick={()=>act("activate",{gift_card_id:c.id})}>Activate / Verify</button></article>)}</div></section>}
 {tab==="sell"&&<form onSubmit={submit} className="form"><h2>Sell / Issue Gift Card</h2>{[["code","Gift card code"],["amount","Amount"],["purchaser_name","Purchaser name"],["recipient_name","Recipient name"],["recipient_phone","Recipient phone"]].map(([k,l])=><label key={k}>{l}<input required={k==="code"||k==="amount"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Expiry date<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value?new Date(e.target.value).toISOString():""})}/></label><button>Sell / Issue</button></form>}
 {tab==="redeem"&&<form onSubmit={doRedeem} className="form"><h2>Redeem Gift Card</h2><label>Code<input required value={redeem.code} onChange={e=>setRedeem({...redeem,code:e.target.value})}/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={redeem.amount} onChange={e=>setRedeem({...redeem,amount:e.target.value})}/></label><label>Order ID (optional)<input value={redeem.order_id||""} onChange={e=>setRedeem({...redeem,order_id:e.target.value})}/></label><label>Notes<input value={redeem.notes} onChange={e=>setRedeem({...redeem,notes:e.target.value})}/></label><button>Redeem</button></form>}
 {tab==="lookup"&&<div className="form"><h2>QR / Code Lookup</h2><input placeholder="Scan or paste gift card code" onChange={e=>setLookup({...lookup,code:e.target.value})}/><button onClick={async()=>{try{const d=await act("lookup",{code:lookup?.code});setLookup(d)}catch{}}}>Lookup</button>{lookup?.balance!==undefined&&<div className="result"><b>{lookup.code}</b><strong>{money(lookup.balance)}</strong><span>{lookup.status}</span></div>}</div>}
 <style jsx>{` .gc{min-height:100vh;background:var(--background);color:var(--text);padding:28px;box-sizing:border-box}.gc header{display:flex;justify-content:space-between;gap:20px;align-items:center}.gc header span{font-size:11px;font-weight:900;letter-spacing:.15em;color:var(--info)}h1{margin:6px 0;font-size:34px}.gc p{color:var(--muted)}button{border:1px solid var(--border);background:var(--surface-2);color:var(--text);padding:11px 15px;border-radius:11px;font-weight:800;cursor:pointer}.gc nav{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.gc nav .active{background:var(--primary);color:#111}.msg{padding:12px;border:1px solid var(--border);border-radius:12px;margin-bottom:15px;font-weight:800}.toolbar{display:flex;gap:10px;margin-bottom:15px}.toolbar input,.form input{width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid var(--border);background:var(--surface);color:var(--text)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.grid article,.form,.result{background:var(--surface);border:1px solid var(--border);border-radius:18px;padding:18px}.row{display:flex;justify-content:space-between;font-size:18px}.grid small{color:var(--muted)}.ledger{margin:14px 0;border-top:1px solid var(--border)}.ledger div{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border);font-size:13px}.form{max-width:650px;display:grid;gap:14px}.form h2{margin-top:0}.form label{display:grid;gap:7px;font-weight:800}.result{margin-top:15px;display:flex;justify-content:space-between;gap:15px}.result strong{font-size:24px}@media(max-width:700px){.gc{padding:16px}.gc header{align-items:flex-start}.grid{grid-template-columns:1fr}.toolbar{flex-direction:column}}`}</style></main>
}
