import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
import {decryptMarketingToken,encryptMarketingToken} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
export async function GET(req){try{const user=await sa(req);const id=String(new URL(req.url).searchParams.get("session_id")||"");if(!id)throw new Error("Selection session is required");const {data,error}=await supabaseCloudAdmin.from("platform_marketing_oauth_sessions").select("id,platform,expires_at,candidates").eq("id",id).eq("user_id",user.id).eq("scope","platform").gt("expires_at",new Date().toISOString()).maybeSingle();if(error)throw error;if(!data)throw new Error("Meta selection session expired. Reconnect.");return NextResponse.json({success:true,...data,candidates:(data.candidates||[]).map(x=>({...x,access_token:undefined}))})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const user=await sa(req);const b=await req.json();const sessionId=String(b.session_id||""),accountId=String(b.account_id||"");if(!sessionId||!accountId)throw new Error("OAuth selection is incomplete");const {data:s,error:se}=await supabaseCloudAdmin.from("platform_marketing_oauth_sessions").select("*").eq("id",sessionId).eq("user_id",user.id).eq("scope","platform").gt("expires_at",new Date().toISOString()).maybeSingle();if(se)throw se;if(!s)throw new Error("Meta selection session expired. Reconnect.");const candidates=Array.isArray(s.candidates)?s.candidates:[];const selected=candidates.find(x=>String(x.id)===accountId||(s.platform==="instagram"&&String(x.instagram_business_account?.id)===accountId));if(!selected)throw new Error("Selected Meta account is not available in this authorization session");const ig=selected.instagram_business_account;const targetId=s.platform==="instagram"?ig.id:selected.id;const targetName=s.platform==="instagram"?(ig.username||ig.name):selected.name;const targetImage=s.platform==="instagram"?(ig.profile_picture_url||selected.profile_image_url):selected.profile_image_url;const token=decryptMarketingToken(selected.access_token);const {data:old}=await supabaseCloudAdmin.from("platform_marketing_connections").select("metadata").eq("platform",s.platform).eq("account_id",targetId).maybeSingle();const {data:connection,error}=await supabaseCloudAdmin.from("platform_marketing_connections").upsert({platform:s.platform,account_id:targetId,account_name:targetName,profile_image_url:targetImage,status:"connected",encrypted_access_token:encryptMarketingToken(token),connected_at:new Date().toISOString(),token_expires_at:s.token_expires_at,metadata:{...(old?.metadata||{}),source:"meta-oauth",page_id:selected.id,linked_page_name:selected.name,pages:candidates.map(p=>({id:p.id,name:p.name,instagram_business_account:p.instagram_business_account}))}},{onConflict:"platform,account_id"}).select("id,platform,account_id,account_name,profile_image_url,status,token_expires_at,metadata").single();if(error)throw error;await supabaseCloudAdmin.from("platform_marketing_oauth_sessions").delete().eq("id",sessionId);await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:user.id,action:"marketing_connected",platform:s.platform,entity_type:"connection",entity_id:connection.id,metadata:{account_id:targetId,account_name:targetName}});return NextResponse.json({success:true,connection})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
