import { requireFeature } from "@/lib/featureGateServer"
import { NextResponse } from "next/server"
import { supabaseCloudAdmin } from "@/lib/supabaseCloudServer"
import { requireApiUser } from "@/lib/serverAuth"
import { resolveRestaurantForUser } from "@/lib/restaurantResolver"
import { requireStaffPermission } from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
async function ctx(req,permission="customers"){const user=await requireApiUser(req);const r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw Error("Restaurant not found");await requireFeature(r.restaurantId, "p2-banquet-events");await requireStaffPermission(user,r.restaurantId,permission);return{user,restaurantId:r.restaurantId}}
export async function GET(req){try{const{restaurantId}=await ctx(req);const [{data:events,error:e1},{data:packages,error:e2},{data:staff,error:e3}]=await Promise.all([supabaseCloudAdmin.from("p2_2_event_enquiries").select("*").eq("restaurant_id",restaurantId).order("event_date",{ascending:true}).limit(200),supabaseCloudAdmin.from("p2_2_packages").select("*").eq("restaurant_id",restaurantId).eq("is_active",true).order("name"),supabaseCloudAdmin.from("profiles").select("id,email,role").eq("restaurant_id",restaurantId).order("email")]);if(e1)throw e1;if(e2)throw e2;if(e3)throw e3;return NextResponse.json({success:true,events:events||[],packages:packages||[],staff:staff||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const b=await req.json();const a=String(b.action||"");const{restaurantId}=await ctx(req,a==="payment"?"payments":"customers");if(a==="create_enquiry"){if(!b.idempotency_key)throw Error("Idempotency key is required");const{data,error}=await supabaseCloudAdmin.rpc("p2_2_create_enquiry",{p_restaurant_id:restaurantId,p_lead_name:b.lead_name||"",p_lead_phone:b.lead_phone||"",p_event_type:b.event_type||"",p_event_date:b.event_date||null,p_start_time:b.start_time||null,p_end_time:b.end_time||null,p_venue:b.venue||"",p_guest_count:Number(b.guest_count||0),p_idempotency_key:b.idempotency_key});if(error)throw error;return NextResponse.json({success:true,event:data})}if(a==="payment"){const{data,error}=await supabaseCloudAdmin.rpc("p2_2_record_payment",{p_restaurant_id:restaurantId,p_enquiry_id:b.enquiry_id,p_quote_id:b.quote_id||null,p_payment_type:b.payment_type||"advance",p_amount:Number(b.amount),p_method:b.payment_method||"cash",p_reference:b.reference||null,p_idempotency_key:b.idempotency_key||crypto.randomUUID()});if(error)throw error;return NextResponse.json({success:true,payment:data})}if(a==="invoice"){const{data,error}=await supabaseCloudAdmin.rpc("p2_2_finalize_invoice",{p_restaurant_id:restaurantId,p_enquiry_id:b.enquiry_id,p_quote_id:b.quote_id,p_idempotency_key:b.idempotency_key||crypto.randomUUID()});if(error)throw error;return NextResponse.json({success:true,invoice:data})}throw Error("Unsupported banquet action")}catch(e){return NextResponse.json({success:false,error:e.message},{status:/permission|authorized|authentication/i.test(e.message||"")?403:400})}}
