import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {verifyOAuthState,encryptMarketingToken,decryptMarketingToken,metaGraphBase,metaJson} from "@/lib/marketingMeta"
import {getMetaServerConfig} from "@/lib/marketingConfig"
export const runtime="nodejs"
export async function GET(req){const appUrl=process.env.NEXT_PUBLIC_APP_URL||new URL(req.url).origin;let redirectPath="/dashboard/marketing?tab=Overview";try{const u=new URL(req.url);const state=verifyOAuthState(u.searchParams.get("state"));redirectPath=state.scope==="platform"?`/super-admin/marketing?tab=${state.platform}`:`/dashboard/marketing?tab=${state.platform}`;const code=u.searchParams.get("code");if(!code)throw new Error(u.searchParams.get("error_description")||"Meta authorization was cancelled");const {data:actor}=await supabaseCloudAdmin.from("profiles").select("id,role,restaurant_id").eq("id",state.userId).maybeSingle();if(!actor)throw new Error("OAuth user session is no longer valid");if(state.scope==="platform"){if(String(actor.role||"").toLowerCase()!=="super_admin")throw new Error("Super Admin access required")}else if(actor.restaurant_id!==state.restaurantId){throw new Error("OAuth restaurant context is no longer valid")}const cfg=await getMetaServerConfig();const appId=cfg.appId,appSecret=cfg.appSecret,redirectUri=cfg.redirectUri||new URL("/api/marketing/meta/oauth/callback",req.url).toString();if(!appId||!appSecret)throw new Error("Meta OAuth server credentials are not configured. Open Marketing → Settings.");const tokenUrl=new URL(`${metaGraphBase()}/oauth/access_token`);tokenUrl.searchParams.set("client_id",appId);tokenUrl.searchParams.set("client_secret",appSecret);tokenUrl.searchParams.set("redirect_uri",redirectUri);tokenUrl.searchParams.set("code",code);const tr=await fetch(tokenUrl);const td=await tr.json();if(!tr.ok||!td.access_token)throw new Error(td.error?.message||"Unable to exchange Meta authorization code");let userAccessToken=td.access_token;
const longUrl=new URL(`${metaGraphBase()}/oauth/access_token`); longUrl.searchParams.set("grant_type","fb_exchange_token"); longUrl.searchParams.set("client_id",appId); longUrl.searchParams.set("client_secret",appSecret); longUrl.searchParams.set("fb_exchange_token",td.access_token);
const lr=await fetch(longUrl); const ld=await lr.json().catch(()=>({})); if(lr.ok&&ld.access_token) userAccessToken=ld.access_token; const expiresIn=Number(ld.expires_in||td.expires_in||0); const tokenExpiresAt=expiresIn>0?new Date(Date.now()+expiresIn*1000).toISOString():null;
const pages=await metaJson("me/accounts",{access_token:userAccessToken,fields:"id,name,access_token,picture,instagram_business_account{id,username,name,profile_picture_url}"});const pageList=(pages.data||[]).map(p=>({id:p.id,name:p.name,profile_image_url:p.picture?.data?.url||"",access_token:encryptMarketingToken(p.access_token||td.access_token),instagram_business_account:p.instagram_business_account||null}));if(!pageList.length)throw new Error("No Facebook Pages were granted to this Meta account");const selected=state.platform==="instagram"?pageList.find(p=>p.instagram_business_account):pageList[0];if(state.platform==="instagram"&&!selected)throw new Error("No Instagram Professional account linked to the authorized Facebook Page");const targetId=state.platform==="instagram"?selected.instagram_business_account.id:selected.id;const targetName=state.platform==="instagram"?(selected.instagram_business_account.username||selected.instagram_business_account.name):selected.name;const targetImage=state.platform==="instagram"?(selected.instagram_business_account.profile_picture_url||selected.profile_image_url):selected.profile_image_url;if(state.scope==="platform"){
  const candidates=pageList.map(p=>({id:p.id,name:p.name,profile_image_url:p.profile_image_url,access_token:p.access_token,instagram_business_account:p.instagram_business_account}));
  const {data:session,error:oe}=await supabaseCloudAdmin.from("platform_marketing_oauth_sessions").insert({user_id:actor.id,scope:"platform",platform:state.platform,token_expires_at:tokenExpiresAt,candidates}).select("id").single();
  if(oe)throw oe;
  return NextResponse.redirect(`${appUrl}/super-admin/marketing?tab=${state.platform}&meta_select=${session.id}`);
}
const {data:session,error:oe}=await supabaseCloudAdmin.from("marketing_oauth_sessions").insert({
  user_id:actor.id,restaurant_id:state.restaurantId,platform:state.platform,token_expires_at:tokenExpiresAt,candidates:pageList
}).select("id").single();
if(oe)throw oe;
return NextResponse.redirect(`${appUrl}/dashboard/marketing?tab=${state.platform}&meta_select=${session.id}`)}catch(e){return NextResponse.redirect(`${appUrl}${redirectPath}${redirectPath.includes("?")?"&":"?"}marketing_error=${encodeURIComponent(e.message||"Meta OAuth failed")}`)}}
