import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {decryptMarketingToken,metaGraphBase} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function enabled(rid,code){const {data}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",rid).eq("plugin_code",code).maybeSingle();return data?.enabled===true}
async function metaInsights(rid,platform){if(!(await enabled(rid,`${platform}-integration`)))return {available:false,metrics:{}};try{const {data:s}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",rid).eq("plugin_code",`${platform}-integration`).maybeSingle();const {data:c}=await supabaseCloudAdmin.from("marketing_connections").select("encrypted_access_token,account_id,status").eq("restaurant_id",rid).eq("platform",platform).eq("status","connected").order("updated_at",{ascending:false}).limit(1).maybeSingle();const token=c?.encrypted_access_token?decryptMarketingToken(c.encrypted_access_token):decryptMarketingToken(s?.config?.access_token),id=c?.account_id||s?.config?.account_id;if(!token||!id)return {available:false,metrics:{}};const sets=platform==="facebook"?["page_impressions","page_post_engagements","page_views_total","page_fans"]:["impressions","reach","profile_views","website_clicks"];let data=null;let error="";for(const metric of [sets.join(","),sets.slice(0,2).join(",")]){const url=new URL(`${metaGraphBase()}/${id}/insights`);url.searchParams.set("metric",metric);url.searchParams.set("period","day");url.searchParams.set("access_token",token);const r=await fetch(url);const d=await r.json().catch(()=>({}));if(r.ok&&!d.error){data=d.data||[];break}error=d.error?.message||`Insights unavailable (${r.status})`}const metrics={};for(const x of data||[]){const name=x.name;const vals=Array.isArray(x.values)?x.values.map(v=>Number(v.value||0)):[];metrics[name]=vals.reduce((a,b)=>a+b,0)}return {available:Boolean(data),metrics,error:data?null:error}}catch(e){return {available:false,metrics:{},error:e.message}}}
export async function GET(req){try{const user=await requireApiUser(req),r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,r.restaurantId,"marketing");const rid=r.restaurantId;const [{count:posts},{count:scheduled},{count:leads},{data:attr},{data:campaigns},fb,ig]=await Promise.all([supabaseCloudAdmin.from("marketing_posts").select("id",{count:"exact",head:true}).eq("restaurant_id",rid),supabaseCloudAdmin.from("marketing_posts").select("id",{count:"exact",head:true}).eq("restaurant_id",rid).eq("status","scheduled"),supabaseCloudAdmin.from("marketing_leads").select("id",{count:"exact",head:true}).eq("restaurant_id",rid),supabaseCloudAdmin.from("marketing_attribution").select("revenue,source,campaign,campaign_id,external_order_id").eq("restaurant_id",rid).limit(10000),supabaseCloudAdmin.from("marketing_campaigns").select("id,name,status,budget").eq("restaurant_id",rid).order("created_at",{ascending:false}),metaInsights(rid,"facebook"),metaInsights(rid,"instagram")]);const bySource={},byCampaign={};let revenue=0;for(const x of attr||[]){const v=Number(x.revenue||0);revenue+=v;bySource[x.source||"unknown"]=(bySource[x.source||"unknown"]||0)+v;const key=x.campaign_id||x.campaign||"Unassigned";byCampaign[key]=(byCampaign[key]||0)+v}return NextResponse.json({success:true,stats:{posts:posts||0,scheduled:scheduled||0,leads:leads||0,attributedRevenue:revenue,bySource,byCampaign,campaigns:campaigns||[],meta:{facebook:fb,instagram:ig}}})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
