"use client"
import { useEffect, useMemo, useState } from "react"
import { supabaseCloud } from "@/lib/supabaseCloud"

const money = n => `₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`
const card={background:"var(--surface)",border:"1px solid var(--border)",borderRadius:18,padding:18}
const input={width:"100%",padding:"11px 12px",borderRadius:10,border:"1px solid var(--border)",background:"var(--background)",color:"inherit",boxSizing:"border-box"}
const btn={padding:"10px 14px",borderRadius:10,border:"1px solid var(--border)",background:"var(--surface)",color:"inherit",cursor:"pointer"}
const primary={...btn,background:"var(--primary,#166534)",color:"#fff",borderColor:"transparent"}

export default function InventoryPro(){
 const [restaurantId,setRestaurantId]=useState(null); const [tab,setTab]=useState("overview"); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false)
 const [items,setItems]=useState([]); const [suppliers,setSuppliers]=useState([]); const [purchases,setPurchases]=useState([]); const [menu,setMenu]=useState([]); const [recipes,setRecipes]=useState([]); const [error,setError]=useState("")
 const [supplier,setSupplier]=useState({name:"",phone:"",email:"",gst_number:"",payment_terms:""})
 const [recipe,setRecipe]=useState({menu_item_id:"",yield_qty:1,notes:""}); const [recipeRows,setRecipeRows]=useState([{inventory_id:"",quantity:"",unit:""}])
 const [po,setPo]=useState({supplier_id:"",po_number:"",expected_date:"",notes:""}); const [poRows,setPoRows]=useState([{inventory_id:"",name:"",quantity:"",unit:"kg",unit_cost:""}])
 const [waste,setWaste]=useState({inventory_id:"",quantity:"",reason:"Wastage"})
 const [cost,setCost]=useState(null)
 const load=async()=>{setLoading(true);setError(""); const {data:u}=await supabaseCloud.auth.getUser(); if(!u?.user){setError("Login required");setLoading(false);return}; const {data:p}=await supabaseCloud.from("profiles").select("restaurant_id").eq("id",u.user.id).maybeSingle(); if(!p?.restaurant_id){setError("Restaurant not linked");setLoading(false);return}; const id=p.restaurant_id;setRestaurantId(id); const [a,b,c,d,e]=await Promise.all([supabaseCloud.from("inventory").select("id,name,quantity,unit,category,cost_price,min_stock,reorder_level,expiry_date").eq("restaurant_id",id).order("name"),supabaseCloud.from("restaurant_suppliers").select("*").eq("restaurant_id",id).order("name"),supabaseCloud.from("purchase_orders").select("*").eq("restaurant_id",id).order("created_at",{ascending:false}).limit(50),supabaseCloud.from("menu_items").select("id,name,price,category").eq("restaurant_id",id).order("name"),supabaseCloud.from("restaurant_recipes").select("id,menu_item_id,yield_qty,notes,restaurant_recipe_items(id,inventory_id,quantity,unit)").eq("restaurant_id",id).order("created_at",{ascending:false})]); if(a.error||b.error||c.error||d.error||e.error)setError(a.error?.message||b.error?.message||c.error?.message||d.error?.message||e.error?.message||"Unable to load inventory workspace"); setItems(a.data||[]);setSuppliers(b.data||[]);setPurchases(c.data||[]);setMenu(d.data||[]);setRecipes(e.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const low=useMemo(()=>items.filter(x=>Number(x.quantity||0)<=Number(x.reorder_level??x.min_stock??0)&&Number(x.quantity||0)>0),[items]); const out=useMemo(()=>items.filter(x=>Number(x.quantity||0)<=0),[items]); const stockValue=useMemo(()=>items.reduce((s,x)=>s+Number(x.quantity||0)*Number(x.cost_price||0),0),[items])
 const addSupplier=async()=>{if(!restaurantId||!supplier.name.trim())return;setSaving(true);const {error:e}=await supabaseCloud.from("restaurant_suppliers").insert({...supplier,restaurant_id:restaurantId});setSaving(false);if(e)setError(e.message);else{setSupplier({name:"",phone:"",email:"",gst_number:"",payment_terms:""});load()}}
 const saveRecipe=async()=>{if(!restaurantId||!recipe.menu_item_id)return;setSaving(true);let {data:r,error:e}=await supabaseCloud.from("restaurant_recipes").upsert({...recipe,restaurant_id:restaurantId},{onConflict:"restaurant_id,menu_item_id"}).select("id").single();if(!e&&r){await supabaseCloud.from("restaurant_recipe_items").delete().eq("recipe_id",r.id);const rows=recipeRows.filter(x=>x.inventory_id&&Number(x.quantity)>0).map(x=>({...x,recipe_id:r.id,quantity:Number(x.quantity)}));if(rows.length) {const q=await supabaseCloud.from("restaurant_recipe_items").insert(rows);e=q.error} if(!e) await supabaseCloud.rpc("phase3_sync_recipe_item_ingredients",{p_recipe_id:r.id})}setSaving(false);if(e)setError(e.message);else{setRecipe({menu_item_id:"",yield_qty:1,notes:""});setRecipeRows([{inventory_id:"",quantity:"",unit:""}]);load()}}
 const createPO=async()=>{if(!restaurantId)return;const rows=poRows.filter(x=>x.name&&Number(x.quantity)>0);if(!rows.length){setError("Add at least one purchase item");return}setSaving(true);const {data:p,error:e}=await supabaseCloud.from("purchase_orders").insert({restaurant_id:restaurantId,supplier_id:po.supplier_id||null,po_number:po.po_number||null,status:"draft",expected_date:po.expected_date||null,notes:po.notes||null,created_by:(await supabaseCloud.auth.getUser()).data.user.id}).select("id").single();if(!e&&p){const q=await supabaseCloud.from("purchase_order_items").insert(rows.map(x=>({purchase_order_id:p.id,inventory_id:x.inventory_id||null,name:x.name,quantity:Number(x.quantity),unit:x.unit,unit_cost:Number(x.unit_cost||0)})));if(q.error)e=q.error}setSaving(false);if(e)setError(e.message);else{setPo({supplier_id:"",po_number:"",expected_date:"",notes:""});setPoRows([{inventory_id:"",name:"",quantity:"",unit:"kg",unit_cost:""}]);load()}}
 const recordWaste=async()=>{if(!waste.inventory_id||Number(waste.quantity)<=0)return;setSaving(true);const {error:e}=await supabaseCloud.rpc("phase3_record_wastage",{p_inventory_id:waste.inventory_id,p_quantity:Number(waste.quantity),p_reason:waste.reason});setSaving(false);if(e)setError(e.message);else{setWaste({inventory_id:"",quantity:"",reason:"Wastage"});load()}}
 const foodCost=async id=>{const {data,e}=await supabaseCloud.rpc("phase3_menu_food_cost",{p_menu_item_id:id});if(e)setError(e.message);else setCost(data)}
 if(loading)return <main style={{padding:24}}>Loading Inventory Pro…</main>
 return <main style={{padding:"20px",maxWidth:1500,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",marginBottom:18}}><div><h1 style={{margin:0}}>📦 Inventory Pro</h1><p style={{margin:"6px 0",opacity:.7}}>Stock • Recipes/BOM • Purchasing • Food Cost • Wastage</p></div><a href="/dashboard/inventory" style={{...btn,textDecoration:"none"}}>Open Inventory</a></div>
  {error&&<div style={{...card,marginBottom:14,borderColor:"#b91c1c",color:"#b91c1c"}}>{error}</div>}
  <div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:12}}>{[["overview","Overview"],["suppliers","Suppliers"],["recipes","Recipes / BOM"],["purchases","Purchasing"],["wastage","Wastage"]].map(([k,l])=><button key={k} style={tab===k?primary:btn} onClick={()=>setTab(k)}>{l}</button>)}</div>
  {tab==="overview"&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[["Items",items.length],["Low Stock",low.length],["Out of Stock",out.length],["Stock Value",money(stockValue)]].map(([l,v])=><div key={l} style={card}><div style={{opacity:.65}}>{l}</div><strong style={{fontSize:24}}>{v}</strong></div>)}</div><div style={{...card,marginTop:14,overflowX:"auto"}}><h3>Low / Out of Stock</h3><table style={{width:"100%",borderCollapse:"collapse"}}><tbody>{[...low,...out].slice(0,20).map(x=><tr key={x.id}><td style={{padding:10}}>{x.name}</td><td>{x.quantity} {x.unit}</td><td>{money(x.cost_price)}</td><td>{Number(x.quantity)<=0?"OUT":"LOW"}</td></tr>)}</tbody></table></div></>}
  {tab==="suppliers"&&<div style={{display:"grid",gridTemplateColumns:"minmax(280px,360px) 1fr",gap:14}}><div style={card}><h3>Add Supplier</h3>{[["name","Name"],["phone","Phone"],["email","Email"],["gst_number","GSTIN"],["payment_terms","Payment Terms"]].map(([k,l])=><input key={k} style={{...input,marginBottom:9}} placeholder={l} value={supplier[k]} onChange={e=>setSupplier({...supplier,[k]:e.target.value})}/>)}<button style={primary} disabled={saving} onClick={addSupplier}>Save Supplier</button></div><div style={card}><h3>Suppliers</h3>{suppliers.map(s=><div key={s.id} style={{padding:"12px 0",borderBottom:"1px solid var(--border)"}}><strong>{s.name}</strong><div style={{opacity:.65}}>{s.phone||"No phone"} {s.gst_number?`• ${s.gst_number}`:""}</div></div>)}</div></div>}
  {tab==="recipes"&&<div style={{display:"grid",gridTemplateColumns:"minmax(300px,460px) 1fr",gap:14}}><div style={card}><h3>Recipe / BOM</h3><select style={{...input,marginBottom:9}} value={recipe.menu_item_id} onChange={e=>setRecipe({...recipe,menu_item_id:e.target.value})}><option value="">Select menu item</option>{menu.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input style={{...input,marginBottom:9}} type="number" min="0.01" step="0.01" value={recipe.yield_qty} onChange={e=>setRecipe({...recipe,yield_qty:Number(e.target.value)})} placeholder="Yield"/>{recipeRows.map((r,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 90px 80px",gap:6,marginBottom:7}}><select style={input} value={r.inventory_id} onChange={e=>{const a=[...recipeRows];a[i].inventory_id=e.target.value;const it=items.find(x=>x.id===e.target.value);a[i].unit=it?.unit||"";setRecipeRows(a)}}><option value="">Ingredient</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input style={input} value={r.quantity} onChange={e=>{const a=[...recipeRows];a[i].quantity=e.target.value;setRecipeRows(a)}} placeholder="Qty"/><button style={btn} onClick={()=>setRecipeRows(recipeRows.filter((_,j)=>j!==i))}>×</button></div>)}<button style={btn} onClick={()=>setRecipeRows([...recipeRows,{inventory_id:"",quantity:"",unit:""}])}>+ Ingredient</button> <button style={primary} disabled={saving} onClick={saveRecipe}>Save Recipe</button></div><div style={card}><h3>Existing Recipes</h3>{recipes.map(r=>{const m=menu.find(x=>x.id===r.menu_item_id);return <div key={r.id} style={{padding:12,borderBottom:"1px solid var(--border)"}}><strong>{m?.name||"Menu Item"}</strong><div style={{opacity:.7}}>{r.restaurant_recipe_items?.length||0} ingredients • Yield {r.yield_qty||1}</div><button style={{...btn,marginTop:7}} onClick={()=>foodCost(r.menu_item_id)}>Calculate Food Cost</button></div>})}{cost&&<pre style={{whiteSpace:"pre-wrap",marginTop:12}}>{JSON.stringify(cost,null,2)}</pre>}</div></div>}
  {tab==="purchases"&&<div style={{display:"grid",gridTemplateColumns:"minmax(300px,480px) 1fr",gap:14}}><div style={card}><h3>Purchase Order</h3><select style={{...input,marginBottom:9}} value={po.supplier_id} onChange={e=>setPo({...po,supplier_id:e.target.value})}><option value="">Supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input style={{...input,marginBottom:9}} placeholder="PO Number" value={po.po_number} onChange={e=>setPo({...po,po_number:e.target.value})}/>{poRows.map((r,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 75px 90px",gap:6,marginBottom:7}}><input style={input} placeholder="Item name" value={r.name} onChange={e=>{const a=[...poRows];a[i].name=e.target.value;setPoRows(a)}}/><input style={input} placeholder="Qty" value={r.quantity} onChange={e=>{const a=[...poRows];a[i].quantity=e.target.value;setPoRows(a)}}/><input style={input} placeholder="Cost" value={r.unit_cost} onChange={e=>{const a=[...poRows];a[i].unit_cost=e.target.value;setPoRows(a)}}/></div>)}<button style={btn} onClick={()=>setPoRows([...poRows,{inventory_id:"",name:"",quantity:"",unit:"kg",unit_cost:""}])}>+ Item</button> <button style={primary} disabled={saving} onClick={createPO}>Create PO</button></div><div style={card}><h3>Purchase Orders</h3>{purchases.map(p=><div key={p.id} style={{padding:12,borderBottom:"1px solid var(--border)"}}><strong>{p.po_number||"Purchase"}</strong><div>{p.status} • {money(p.total)}</div></div>)}</div></div>}
  {tab==="wastage"&&<div style={{...card,maxWidth:600}}><h3>Record Wastage</h3><select style={{...input,marginBottom:9}} value={waste.inventory_id} onChange={e=>setWaste({...waste,inventory_id:e.target.value})}><option value="">Select stock item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} — {x.quantity} {x.unit}</option>)}</select><input style={{...input,marginBottom:9}} type="number" min="0.01" step="0.01" placeholder="Quantity" value={waste.quantity} onChange={e=>setWaste({...waste,quantity:e.target.value})}/><input style={{...input,marginBottom:9}} placeholder="Reason" value={waste.reason} onChange={e=>setWaste({...waste,reason:e.target.value})}/><button style={primary} disabled={saving} onClick={recordWaste}>Record Wastage</button></div>}
 </main>
}
