"use client"
import {useEffect,useMemo,useState} from "react"
import {supabaseCloud} from "@/lib/supabaseCloud"
const box={background:"#fff",border:"1px solid #e4e9ef",borderRadius:16,padding:18,boxShadow:"0 8px 28px rgba(15,23,42,.05)"}
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`
export default function EnterpriseHQ(){
 const [rid,setRid]=useState(""),[d,setD]=useState(null),[tab,setTab]=useState("overview"),[days,setDays]=useState(30),[loading,setLoading]=useState(true),[msg,setMsg]=useState("")
 const [form,setForm]=useState({name:"",category:"",base_price:"",catalog_item_id:"",restaurant_id:"",price:"",from_restaurant_id:"",to_restaurant_id:"",inventory_id:"",item_name:"",quantity:"",unit:"",staff_id:"",effective_date:"",reason:""})
 async function load(){setLoading(true);try{const {data:s}=await supabaseCloud.auth.getSession();const token=s?.session?.access_token;if(!token)throw Error("Login required");const {data:m,error}=await supabaseCloud.from("enterprise_members").select("enterprise_id").eq("user_id",s.session.user.id).limit(1).maybeSingle();if(error)throw error;if(!m)throw Error("Enterprise membership not found");setRid(m.enterprise_id);const r=await fetch(`/api/enterprise/hq?enterprise_id=${m.enterprise_id}&days=${days}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const p=await r.json();if(!r.ok||!p.success)throw Error(p.error||"Unable to load HQ");setD(p)}catch(e){setMsg(e.message||"Unable to load HQ")}finally{setLoading(false)}}
 useEffect(()=>{load()},[days])
 const outlets=d?.outlets||[],catalog=d?.catalog||[],prices=d?.prices||[],transfers=d?.transfers||[],approvals=d?.approvals||[],moves=d?.staff_movements||[],snap=d?.snapshots||[]
 const totals=useMemo(()=>snap.reduce((a,x)=>({revenue:a.revenue+Number(x.revenue||0),orders:a.orders+Number(x.orders_count||0),refunds:a.refunds+Number(x.refunds||0),expenses:a.expenses+Number(x.expenses||0)}),{revenue:0,orders:0,refunds:0,expenses:0}),[snap])
 async function act(action,extra={}){setMsg("");try{const {data:s}=await supabaseCloud.auth.getSession();const r=await fetch("/api/enterprise/hq",{method:"POST",headers:{Authorization:`Bearer ${s.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action,enterprise_id:rid,...extra})});const p=await r.json();if(!r.ok||!p.success)throw Error(p.error||"Action failed");setMsg("Saved successfully");load()}catch(e){setMsg(e.message)}}
 if(loading)return <main style={{padding:28}}>Loading Enterprise HQ…</main>
 return <main style={{minHeight:"100vh",padding:"24px clamp(12px,3vw,40px) 50px",background:"#f6f8fb"}}>
  <header style={{...box,display:"flex",justifyContent:"space-between",gap:15,alignItems:"center",marginBottom:16,flexWrap:"wrap"}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.5,opacity:.6}}>ANAIRA ENTERPRISE HQ</div><h1 style={{margin:"5px 0"}}>{d?.enterprise?.name||"Enterprise Headquarters"}</h1><span style={{opacity:.65}}>Multi-outlet control, central operations and consolidated finance</span></div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 Days</option><option value={30}>30 Days</option><option value={90}>90 Days</option><option value={365}>365 Days</option></select></header>
  {msg&&<div style={{...box,marginBottom:14}}>{msg}</div>}
  <nav style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:10}}>{[["overview","Overview"],["outlets","Outlets"],["comparison","Comparison"],["menu","Central Menu"],["pricing","Pricing"],["inventory","Inventory"],["transfers","Transfers"],["approvals","Approvals"],["staff","Staff Movement"],["reports","Reports"],["accounting","Accounting"],["devices","Devices"],["audit","Audit"]].map(x=><button key={x[0]} onClick={()=>setTab(x[0])} style={{padding:"10px 14px",borderRadius:10,border:"1px solid #dbe2ea",background:tab===x[0]?"#153b2e":"white",color:tab===x[0]?"white":"#1f2937",whiteSpace:"nowrap"}}>{x[1]}</button>)}</nav>
  {tab==="overview"&&<><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,margin:"8px 0 16px"}}>{[["Revenue",money(totals.revenue)],["Orders",totals.orders],["AOV",money(totals.orders?totals.revenue/totals.orders:0)],["Refunds",money(totals.refunds)],["Expenses",money(totals.expenses)],["Outlets",outlets.length],["Pending Approvals",approvals.length],["Transfers",transfers.length]].map(x=><div style={box} key={x[0]}><small style={{opacity:.6}}>{x[0]}</small><div style={{fontSize:25,fontWeight:800,marginTop:5}}>{x[1]}</div></div>)}</section><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><Panel title="Outlet Network">{outlets.map(o=><div style={row} key={o.id}><b>{o.outlet_name||o.restaurant_id}</b><span>{o.outlet_code||"—"}</span></div>)}</Panel><Panel title="Recent Transfers">{transfers.slice(0,8).map(t=><div style={row} key={t.id}><b>{t.item_name}</b><span>{t.quantity} {t.unit||""} · {t.status}</span></div>)}</Panel><Panel title="Targets">{(d?.targets||[]).slice(0,8).map(t=><div style={row} key={t.id}><b>{t.target_type}</b><span>{money(t.actual_value)} / {money(t.target_value)}</span></div>)}</Panel></div></>}
  {tab==="outlets"&&<Panel title="Outlet Network">{outlets.map(o=><div style={row} key={o.id}><b>{o.outlet_name||o.restaurant_id}</b><span>{o.outlet_code} · {o.is_active?"Active":"Inactive"}</span></div>)}</Panel>}
  {tab==="comparison"&&<Panel title="Outlet Comparison"><div style={{overflowX:"auto"}}><table style={table}><thead><tr><th>Outlet</th><th>Revenue</th><th>Orders</th><th>AOV</th><th>Expenses</th></tr></thead><tbody>{outlets.map(o=>{const s=snap.filter(x=>x.restaurant_id===o.restaurant_id);const rev=s.reduce((a,x)=>a+Number(x.revenue||0),0),ord=s.reduce((a,x)=>a+Number(x.orders_count||0),0),exp=s.reduce((a,x)=>a+Number(x.expenses||0),0);return <tr key={o.id}><td>{o.outlet_name}</td><td>{money(rev)}</td><td>{ord}</td><td>{money(ord?rev/ord:0)}</td><td>{money(exp)}</td></tr>})}</tbody></table></div></Panel>}
  {tab==="menu"&&<div style={{display:"grid",gridTemplateColumns:"minmax(280px,360px) 1fr",gap:14}}><Panel title="Add Central Menu Item"><form onSubmit={e=>{e.preventDefault();act("menu_create",form)}}><input required placeholder="Item name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input type="number" min="0" placeholder="Base price" value={form.base_price} onChange={e=>setForm({...form,base_price:e.target.value})}/><button>Add Item</button></form></Panel><Panel title="Master Menu">{catalog.map(c=><div style={row} key={c.id}><b>{c.name}</b><span>{c.category||"—"} · {money(c.base_price)}</span></div>)}</Panel></div>}
  {tab==="pricing"&&<div style={{display:"grid",gridTemplateColumns:"minmax(280px,380px) 1fr",gap:14}}><Panel title="Set Outlet Price"><form onSubmit={e=>{e.preventDefault();act("price_upsert",form)}}><select required value={form.catalog_item_id} onChange={e=>setForm({...form,catalog_item_id:e.target.value})}><option value="">Menu item</option>{catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select required value={form.restaurant_id} onChange={e=>setForm({...form,restaurant_id:e.target.value})}><option value="">Outlet</option>{outlets.map(o=><option key={o.restaurant_id} value={o.restaurant_id}>{o.outlet_name}</option>)}</select><input required type="number" min="0" step="0.01" placeholder="Outlet price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><button>Save Price</button></form></Panel><Panel title="Outlet Pricing"><p style={{opacity:.65}}>Central catalog remains the master item source; outlet prices are independent overrides.</p>{catalog.map(c=><div style={row} key={c.id}><b>{c.name}</b><span>{prices.filter(p=>p.catalog_item_id===c.id).map(p=>`${outlets.find(o=>o.restaurant_id===p.restaurant_id)?.outlet_name||"Outlet"}: ${money(p.price)}`).join(" · ")||"No outlet price"}</span></div>)}</Panel></div>}
  {tab==="inventory"&&<Panel title="Central Inventory Visibility"><p style={{opacity:.65}}>HQ transfer engine uses each outlet's real inventory stock. Create transfers from the Transfers tab.</p><div style={row}><b>Outlet stock isolation</b><span>Enabled</span></div><div style={row}><b>Transfer stock deduction</b><span>Source − / Destination +</span></div></Panel>}
  {tab==="transfers"&&<div style={{display:"grid",gridTemplateColumns:"minmax(280px,380px) 1fr",gap:14}}><Panel title="Request Transfer"><form onSubmit={e=>{e.preventDefault();act("transfer_request",form)}}><select value={form.from_restaurant_id} onChange={e=>setForm({...form,from_restaurant_id:e.target.value})}><option value="">From outlet</option>{outlets.map(o=><option key={o.restaurant_id} value={o.restaurant_id}>{o.outlet_name}</option>)}</select><select value={form.to_restaurant_id} onChange={e=>setForm({...form,to_restaurant_id:e.target.value})}><option value="">To outlet</option>{outlets.map(o=><option key={o.restaurant_id} value={o.restaurant_id}>{o.outlet_name}</option>)}</select><input placeholder="Inventory UUID" value={form.inventory_id} onChange={e=>setForm({...form,inventory_id:e.target.value})}/><input required placeholder="Item name" value={form.item_name} onChange={e=>setForm({...form,item_name:e.target.value})}/><input required type="number" min="0.001" placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input placeholder="Unit" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><button>Request Transfer</button></form></Panel><Panel title="Transfer Queue">{transfers.map(t=><div style={row} key={t.id}><div><b>{t.item_name}</b><small>{t.quantity} {t.unit||""}</small></div><span>{t.status} {t.status==="requested"&&<button onClick={()=>act("transfer_decide",{id:t.id,status:"approved"})}>Approve</button>} {t.status==="approved"&&<button onClick={()=>act("transfer_receive",{id:t.id})}>Receive</button>}</span></div>)}</Panel></div>}
  {tab==="approvals"&&<Panel title="Approval Center">{approvals.map(a=><div style={row} key={a.id}><div><b>{a.request_type}</b><small>{a.reason||"No reason"}</small></div><span><button onClick={()=>act("approval_decide",{id:a.id,status:"approved"})}>Approve</button><button onClick={()=>act("approval_decide",{id:a.id,status:"rejected"})}>Reject</button></span></div>)}{!approvals.length&&<p>No pending approvals.</p>}</Panel>}
  {tab==="staff"&&<Panel title="Staff Movement"><form onSubmit={e=>{e.preventDefault();act("staff_move",form)}}><input required placeholder="Staff UUID" value={form.staff_id} onChange={e=>setForm({...form,staff_id:e.target.value})}/><select value={form.from_restaurant_id} onChange={e=>setForm({...form,from_restaurant_id:e.target.value})}><option value="">From outlet</option>{outlets.map(o=><option key={o.restaurant_id} value={o.restaurant_id}>{o.outlet_name}</option>)}</select><select value={form.to_restaurant_id} onChange={e=>setForm({...form,to_restaurant_id:e.target.value})}><option value="">To outlet</option>{outlets.map(o=><option key={o.restaurant_id} value={o.restaurant_id}>{o.outlet_name}</option>)}</select><input type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/><input placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button>Request Movement</button></form>{moves.map(x=><div style={row} key={x.id}><b>{x.staff_id.slice(0,8)}</b><span>{x.status} · {x.effective_date}</span></div>)}</Panel>}
  {tab==="reports"&&<Reports enterpriseId={rid}/>} {tab==="accounting"&&<Accounting enterpriseId={rid}/>} {tab==="devices"&&<Panel title="Enterprise Devices">{(d?.devices||[]).map(x=><div style={row} key={x.id}><b>{x.device_name||x.device_key}</b><span>{x.device_type} · {x.status} · {x.last_seen_at?new Date(x.last_seen_at).toLocaleString():"Never seen"}</span></div>)}</Panel>}
  {tab==="audit"&&<Panel title="Audit"><p>All HQ mutations write to enterprise_audit_logs. Use the existing audit workspace for full historical filtering.</p></Panel>}
 </main>
}
function Reports({enterpriseId}){const [d,setD]=useState(null);useEffect(()=>{(async()=>{const {data:s}=await supabaseCloud.auth.getSession();const end=new Date().toISOString().slice(0,10),start=new Date(Date.now()-29*86400000).toISOString().slice(0,10);const r=await fetch(`/api/enterprise/hq?enterprise_id=${enterpriseId}&tab=reports&start=${start}&end=${end}`,{headers:{Authorization:`Bearer ${s.session.access_token}`}});const x=await r.json();setD(x.data)})()},[enterpriseId]);return <Panel title="Consolidated Reports">{d?.outlets?.map((x,i)=><div style={row} key={i}><b>{x.outlet_name}</b><span>{money(x.revenue)} · {x.orders} orders · Expenses {money(x.expenses)}</span></div>)}<hr/><div style={row}><b>Group Revenue</b><strong>{money(d?.group_revenue)}</strong></div><div style={row}><b>Group Expenses</b><strong>{money(d?.group_expenses)}</strong></div></Panel>}
function Accounting({enterpriseId}){const [d,setD]=useState(null);useEffect(()=>{(async()=>{const {data:s}=await supabaseCloud.auth.getSession();const end=new Date().toISOString().slice(0,10),start=new Date(Date.now()-29*86400000).toISOString().slice(0,10);const r=await fetch(`/api/enterprise/hq?enterprise_id=${enterpriseId}&tab=accounting&start=${start}&end=${end}`,{headers:{Authorization:`Bearer ${s.session.access_token}`}});const x=await r.json();setD(x.data)})()},[enterpriseId]);return <Panel title="Group Accounting"><div style={{overflowX:"auto"}}><table style={table}><thead><tr><th>Date</th><th>Account</th><th>Debit</th><th>Credit</th><th>Source</th></tr></thead><tbody>{(d?.journal||[]).map(j=><tr key={j.id}><td>{j.entry_date}</td><td>{j.account_name||j.account_code}</td><td>{money(j.debit)}</td><td>{money(j.credit)}</td><td>{j.source_type}</td></tr>)}</tbody></table></div></Panel>}
function Panel({title,children}){return <section style={box}><h2 style={{marginTop:0}}>{title}</h2>{children}</section>}
const row={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",padding:"11px 0",borderBottom:"1px solid #eef1f4",flexWrap:"wrap"};const table={width:"100%",borderCollapse:"collapse"};
