"use client"
import { useEffect,useState } from "react"
import { supabaseCloud } from "@/lib/supabaseCloud"
import { ResponsiveContainer,LineChart,Line,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,PieChart,Pie,Cell } from "recharts"
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`
const pct=n=>`${Number(n||0).toFixed(1)}%`
const COLORS=["#0f766e","#2563eb","#d97706","#7c3aed","#dc2626","#0891b2"]
export default function P111(){
 const [days,setDays]=useState(30),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true)
 useEffect(()=>{let dead=false;(async()=>{try{setLoading(true);const {data:a}=await supabaseCloud.auth.getUser();if(!a?.user)throw Error("Please sign in again.");const {data:p,error:pe}=await supabaseCloud.from("profiles").select("restaurant_id").eq("id",a.user.id).single();if(pe)throw pe;const {data:s}=await supabaseCloud.auth.getSession();const r=await fetch(`/api/reports/p1-11?restaurant_id=${p.restaurant_id}&days=${days}`,{headers:{Authorization:`Bearer ${s.session?.access_token||""}`},cache:"no-store"});const x=await r.json();if(!r.ok||!x.success)throw Error(x.error||"Analytics unavailable");if(!dead)setData(x.data)}catch(e){if(!dead){setError(e.message);setData(null)}}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[days])
 const p=data?.pnl||{},fc=data?.food_cost||{},ltv=data?.customer_ltv||{},iv=data?.inventory_variance||{}
 const exportCsv=()=>{if(!data)return;const rows=[["P1.11 Advanced Reporting"],["Metric","Value"],["Gross Revenue",p.gross_revenue],["Net Revenue",p.net_revenue],["COGS",p.cogs],["Food Cost %",p.food_cost_pct],["Operating Expenses",p.operating_expenses],["Operating Profit",p.operating_profit],["Customer LTV",ltv.avg_ltv],["Inventory Value",iv.current_inventory_value]];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`anaira-p1.11-${days}days.csv`;a.click()}
 return <main style={S.page}><header style={S.header}><div><small style={S.kicker}>ANAIRA P1.11</small><h1 style={S.h1}>Advanced Reporting</h1><p style={S.sub}>Final analytics across finance, operations, customers, marketing and forecasting.</p></div><div style={S.actions}><select value={days} onChange={e=>setDays(+e.target.value)} style={S.select}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">365 days</option></select><button onClick={exportCsv} style={S.button}>Export CSV</button></div></header>{error&&<div style={S.error}>{error}</div>}{loading?<div style={S.loading}>Loading final analytics…</div>:data&&<>
 <div style={S.kpis}><K t="Net Revenue" v={money(p.net_revenue)} m={`Gross ${money(p.gross_revenue)}`}/><K t="COGS" v={money(p.cogs)} m={`Food cost ${pct(p.food_cost_pct)}`}/><K t="Operating Profit" v={money(p.operating_profit)} m={`Expenses ${money(p.operating_expenses)}`}/><K t="Customer LTV" v={money(ltv.avg_ltv)} m={`${ltv.customers||0} customers`}/></div>
 <div style={S.grid}><Panel title="P&L + COGS Trend"><ResponsiveContainer width="100%" height={290}><LineChart data={data.daily||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={v=>money(v)}/><Line dataKey="revenue" stroke="#0f766e" strokeWidth={3}/><Line dataKey="cogs" stroke="#dc2626" strokeWidth={2}/></LineChart></ResponsiveContainer></Panel><Panel title="Payment Settlement"><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={data.payment_settlement||[]} dataKey="amount" nameKey="method" outerRadius={95} label>{(data.payment_settlement||[]).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer></Panel></div>
 <div style={S.grid}><Panel title="Outlet Comparison"><Table rows={data.outlet_comparison||[]} cols={["outlet_name","orders","revenue"]} moneyCols={["revenue"]}/></Panel><Panel title="Staff Performance"><Table rows={data.staff_performance||[]} cols={["staff_name","orders","revenue","avg_order"]} moneyCols={["revenue","avg_order"]}/></Panel></div>
 <div style={S.grid}><Panel title="Kitchen Performance"><Table rows={data.kitchen_performance||[]} cols={["station_name","tickets","avg_prep_minutes","on_time"]}/></Panel><Panel title="Aggregator Profitability"><Table rows={data.aggregator_profitability||[]} cols={["provider","orders","gross_value","commission","net_payout","contribution"]} moneyCols={["gross_value","commission","net_payout","contribution"]}/></Panel></div>
 <div style={S.grid}><Panel title="Inventory Variance"><Rows items={[["Current inventory value",money(iv.current_inventory_value)],["Theoretical COGS",money(iv.theoretical_cogs)],["Actual COGS",money(iv.actual_cogs)],["Recipe variance",money(iv.recipe_variance)]]}/></Panel><Panel title="Food Cost"><Rows items={[["COGS",money(fc.cogs)],["Net revenue",money(fc.net_revenue)],["Food cost %",pct(fc.food_cost_pct)],["Variance",money(fc.variance)]]}/></Panel></div>
 <div style={S.grid}><Panel title="Marketing ROI"><Table rows={data.marketing_roi||[]} cols={["campaign","attributed_revenue","budget","roi_pct"]} moneyCols={["attributed_revenue","budget"]}/></Panel><Panel title="Customer LTV"><Rows items={[["Customers",ltv.customers],["Average LTV",money(ltv.avg_ltv)],["Lifetime revenue",money(ltv.lifetime_revenue)],["Average orders",Number(ltv.avg_orders||0).toFixed(1)]]}/></Panel></div>
 <Panel title="Forecasting Dataset"><Table rows={(data.forecasting_datasets||[]).slice(-30)} cols={["date","revenue","cogs","orders","revenue_7d_avg","cogs_7d_avg","orders_7d_avg"]} moneyCols={["revenue","cogs","revenue_7d_avg","cogs_7d_avg"]}/></Panel>
 </>}</main>
}
function K({t,v,m}){return <div style={S.kpi}><span>{t}</span><strong>{v}</strong><small>{m}</small></div>}
function Panel({title,children}){return <section style={S.panel}><h2>{title}</h2>{children}</section>}
function Rows({items}){return <div>{items.map(([a,b])=><div key={a} style={S.row}><span>{a}</span><b>{b}</b></div>)}</div>}
function Table({rows,cols,moneyCols=[]}){return <div style={{overflowX:"auto"}}><table style={S.table}><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{moneyCols.includes(c)?money(r[c]):String(r[c]??"—")}</td>)}</tr>)}</tbody></table></div>}
const S={page:{minHeight:"100vh",padding:"28px clamp(14px,3vw,40px) 50px",background:"#f6f8fb",color:"#142033"},header:{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,flexWrap:"wrap",marginBottom:22},kicker:{fontSize:12,fontWeight:800,letterSpacing:1.5,opacity:.6},h1:{margin:"5px 0",fontSize:"clamp(27px,4vw,38px)"},sub:{margin:0,opacity:.65},actions:{display:"flex",gap:9},select:{padding:"11px 13px",border:"1px solid #d7dde7",borderRadius:10,background:"white"},button:{padding:"11px 15px",border:0,borderRadius:10,background:"#153b2e",color:"white",fontWeight:800},error:{padding:14,background:"#fee2e2",color:"#991b1b",borderRadius:12},loading:{padding:60,textAlign:"center"},kpis:{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:15},kpi:{background:"white",padding:18,borderRadius:16,border:"1px solid #e5eaf0",display:"grid",gap:5},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:15,marginBottom:15},panel:{background:"white",padding:18,borderRadius:16,border:"1px solid #e5eaf0",minWidth:0},row:{display:"flex",justifyContent:"space-between",padding:"13px 0",borderBottom:"1px solid #edf0f4"},table:{width:"100%",borderCollapse:"collapse",fontSize:13},th:{},td:{padding:"10px 8px",borderBottom:"1px solid #edf0f4",whiteSpace:"nowrap"}}
