'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabaseCloud} from '@/lib/supabaseCloud'
import {useAuth} from '@/components/AuthProvider'

const PRESETS={
  system:{title:'System Reliability',eyebrow:'P0 · CORE POS',desc:'Offline queue, retry state, sync conflicts, aggregator events and idempotency audit.',tabs:[['conflicts','Sync Conflicts','p0_sync_conflicts'],['offline','Offline Events','offline_pos_events'],['aggregator','Aggregator Events','p0_aggregator_events'],['idempotency','Idempotency','p0_idempotency_keys']]},
  terminals:{title:'Payment Terminal HQ',eyebrow:'P1 · ADVANCED OPERATIONS',desc:'Terminal registry, health, callback events and reconciliation ledger.',tabs:[['terminals','Terminals','payment_terminals'],['health','Terminal Transactions','payment_terminal_transactions'],['callbacks','Callback Logs','payment_terminal_callbacks'],['recon','Reconciliation','payment_terminal_reconciliation']]},
  marketing:{title:'Marketing Automation',eyebrow:'P1 · ADVANCED OPERATIONS',desc:'Campaigns, audience triggers, delivery runs and performance monitoring.',tabs:[['campaigns','Campaigns','marketing_campaigns'],['runs','Campaign Runs','restaurant_campaign_runs'],['messages','Message Events','platform_marketing_message_events']]},
  banquetops:{title:'Banquet Operations',eyebrow:'P2 · ADVANCED OPERATIONS',desc:'Event operations checklist, staff assignment, inventory reservation, contract and profitability visibility.',tabs:[['operations','Operations Checklist','p2_2_event_operations'],['staff','Staff Assignments','p2_2_event_staff_assignments'],['contracts','Contracts','p2_2_event_contracts'],['profit','Profitability','p2_2_event_profitability']]},
  kioskops:{title:'Kiosk Control Center',eyebrow:'P2 · ADVANCED OPERATIONS',desc:'Kiosk configuration, events, upsell rules, menu cache and device activity.',tabs:[['kiosks','Kiosk Registry','p2_3_kiosks'],['events','Kiosk Events','p2_3_kiosk_events'],['upsells','Upsell Rules','p2_3_kiosk_upsells'],['cache','Menu Cache','p2_3_kiosk_menu_cache']]},
  displayops:{title:'Customer Display Control',eyebrow:'P2 · ADVANCED OPERATIONS',desc:'Display registry, live sessions and display events for dual-screen POS.',tabs:[['displays','Displays','p2_4_customer_displays'],['sessions','Sessions','p2_4_display_sessions'],['events','Display Events','restaurant_display_events']]},
  deviceops:{title:'Device Health & Audit',eyebrow:'P2 · ADVANCED OPERATIONS',desc:'Heartbeat, health, configuration drift, replacement and audit trail.',tabs:[['devices','Devices','p2_5_devices'],['groups','Device Groups','p2_5_device_groups'],['audit','Audit Trail','p2_5_device_audit']]},
  aiops:{title:'AI Model Governance',eyebrow:'P2 · ADVANCED OPERATIONS',desc:'Model runs, backtests, forecasts, recommendation approvals and risk signals.',tabs:[['models','Model Runs','p2_6_model_runs'],['backtests','Backtests','p2_6_backtests'],['recommendations','Recommendations','p2_6_recommendations'],['risks','Risk Signals','p2_6_risk_signals']]}
}

function label(k){return String(k||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function value(v){if(v==null)return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)}
export default function FeatureDataConsole({kind='system'}){
 const cfg=PRESETS[kind]||PRESETS.system; const {restaurantId}=useAuth(); const [tab,setTab]=useState(cfg.tabs[0][0]); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [q,setQ]=useState('');
 const active=cfg.tabs.find(x=>x[0]===tab)||cfg.tabs[0];
 async function load(){setLoading(true);setError('');try{let query=supabaseCloud.from(active[2]).select('*').limit(100); if(restaurantId) query=query.eq('restaurant_id',restaurantId); const {data,error}=await query; if(error)throw error; setRows(data||[])}catch(e){setError(e.message||'Unable to load data')}finally{setLoading(false)}}
 useEffect(()=>{load()},[tab,restaurantId])
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase(); if(!s)return rows;return rows.filter(r=>JSON.stringify(r).toLowerCase().includes(s))},[rows,q]);
 const columns=useMemo(()=>{const keys=[];filtered.slice(0,20).forEach(r=>Object.keys(r||{}).forEach(k=>{if(!keys.includes(k)&&!['restaurant_id','payload','local_data','incoming_data','metadata','config','capabilities','response','action_payload','features','metrics','hyperparameters'].includes(k))keys.push(k)}));return keys.slice(0,10)},[filtered]);
 return <main style={{padding:'26px',maxWidth:1500,margin:'0 auto',color:'var(--text)'}}><header style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:900,letterSpacing:1.5,color:'var(--primary)'}}>{cfg.eyebrow}</div><h1 style={{margin:'5px 0'}}>{cfg.title}</h1><p style={{color:'var(--muted)',margin:0}}>{cfg.desc}</p></div><button onClick={load}>↻ Refresh</button></header><nav style={{display:'flex',gap:8,flexWrap:'wrap',margin:'20px 0'}}>{cfg.tabs.map(x=><button key={x[0]} onClick={()=>setTab(x[0])} style={{fontWeight:800,borderRadius:10,padding:'9px 13px',background:tab===x[0]?'var(--primary)':'var(--surface)',color:tab===x[0]?'#111':'var(--text)',border:'1px solid var(--border)'}}>{x[1]}</button>)}</nav><section style={{display:'flex',gap:10,marginBottom:12}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search records…' style={{flex:1,padding:11,borderRadius:10,border:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)'}}/><span style={{padding:11,color:'var(--muted)'}}>{filtered.length} records</span></section>{error&&<div style={{padding:14,borderRadius:12,border:'1px solid #d66',marginBottom:12}}>⚠️ {error}</div>}{loading?<div>Loading…</div>:filtered.length===0?<div style={{padding:24,border:'1px solid var(--border)',borderRadius:14,background:'var(--surface)'}}>No records for this restaurant yet.</div>:<div style={{overflowX:'auto',border:'1px solid var(--border)',borderRadius:14,background:'var(--surface)'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{columns.map(c=><th key={c} style={{textAlign:'left',padding:12,borderBottom:'1px solid var(--border)',whiteSpace:'nowrap'}}>{label(c)}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id||JSON.stringify(r)}>{columns.map(c=><td key={c} style={{padding:11,borderBottom:'1px solid var(--border)',maxWidth:280,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}} title={value(r[c])}>{value(r[c])}</td>)}</tr>)}</tbody></table></div>}</main>
}
