'use client';
import {useEffect,useMemo,useState} from 'react';
const TYPES=[['pos','POS'],['kiosk','Kiosk'],['kds','KDS'],['calling','Calling Device'],['customer_display','Customer Display'],['printer','Printer'],['payment_terminal','Payment Terminal'],['scanner','Scanner']];
export default function DeviceHQ(){const[d,setD]=useState([]),[g,setG]=useState([]),[f,setF]=useState('all'),[msg,setMsg]=useState(''),[form,setForm]=useState({device_id:'',device_type:'pos',name:'',app_version:'',group_id:''});
async function load(){const r=await fetch('/api/device-hq');const j=await r.json();if(!r.ok)throw Error(j.error);setD(j.devices||[]);setG(j.groups||[])}useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
const vis=useMemo(()=>d.filter(x=>f==='all'||x.device_type===f||(f==='online'&&x.online_status==='online')||(f==='offline'&&x.online_status==='offline')||(f==='disabled'&&x.status==='disabled')),[d,f]);
async function post(b){const r=await fetch('/api/device-hq',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
async function reg(e){e.preventDefault();try{await post({action:'register',...form,group_id:form.group_id||null});setForm({device_id:'',device_type:'pos',name:'',app_version:'',group_id:''});setMsg('Device registered');await load()}catch(e){setMsg(e.message)}}
async function stat(id,s){try{await post({action:'status',id,status:s,reason:'Device HQ'});await load()}catch(e){setMsg(e.message)}}
async function addGroup(){const name=prompt('Device group name');if(!name)return;try{await post({action:'group',name});await load()}catch(e){setMsg(e.message)}}
return <main style={{padding:24,maxWidth:1500,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:12}}><div><h1>Device HQ</h1><p>Central device registration, health and lifecycle management.</p></div><button onClick={addGroup}>+ Device Group</button></header><nav style={{display:'flex',gap:8,flexWrap:'wrap',margin:'18px 0'}}>{[['all','All'],['online','Online'],['offline','Offline'],['disabled','Disabled'],...TYPES].map(x=><button key={x[0]} onClick={()=>setF(x[0])}>{x[1]}</button>)}</nav><form onSubmit={reg} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,padding:16,border:'1px solid #ddd',borderRadius:12}}><input required placeholder='Device ID' value={form.device_id} onChange={e=>setForm({...form,device_id:e.target.value})}/><input required placeholder='Device name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.device_type} onChange={e=>setForm({...form,device_type:e.target.value})}>{TYPES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input placeholder='App version' value={form.app_version} onChange={e=>setForm({...form,app_version:e.target.value})}/><select value={form.group_id} onChange={e=>setForm({...form,group_id:e.target.value})}><option value=''>No group</option>{g.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button>Register / Reconnect</button></form>{msg&&<p>{msg}</p>}<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:14,marginTop:20}}>{vis.map(x=><article key={x.id} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><b>{x.name}</b><div>{TYPES.find(t=>t[0]===x.device_type)?.[1]}</div><small>ID: {x.device_id}</small><br/><small>Group: {x.p2_5_device_groups?.name||'—'}</small><br/><small>Online: {x.online_status} · Health: {x.health_status}</small><br/><small>Version: {x.app_version||'—'} · Config {x.config_version}/{x.desired_config_version}</small><br/><small>Last seen: {x.last_seen_at?new Date(x.last_seen_at).toLocaleString():'Never'}</small><div style={{marginTop:12,display:'flex',gap:8}}>{x.status==='enabled'?<button onClick={()=>stat(x.id,'disabled')}>Disable</button>:<button onClick={()=>stat(x.id,'enabled')}>Enable</button>}<button onClick={()=>stat(x.id,'maintenance')}>Maintenance</button></div></article>)}</section></main>}
