import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
import {decryptMarketingToken,metaGraphBase,isMarketingTokenExpired} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
const metrics={facebook:["page_impressions","page_reactions","page_post_engagements","page_fans"],instagram:["reach","impressions","likes","comments","saves","shares","profile_views","follows_count"]}
export async function GET(req){try{await sa(req);const platform=String(new URL(req.url).searchParams.get("platform")||"facebook").toLowerCase();if(!metrics[platform])throw new Error("Insights are available for Facebook and Instagram");const {data:c,error}=await supabaseCloudAdmin.from("platform_marketing_connections").select("id,platform,account_id,account_name,status,encrypted_access_token,token_expires_at").eq("platform",platform).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!c?.account_id||!c.encrypted_access_token)throw new Error(`${platform} is not connected`);if(isMarketingTokenExpired(c.token_expires_at))return NextResponse.json({success:false,error:"Meta token is expired or expiring. Reconnect the account."},{status:409});const token=decryptMarketingToken(c.encrypted_access_token);const path=platform==="facebook"?`${c.account_id}/insights`:`${c.account_id}/insights`;const url=new URL(`${metaGraphBase()}/${path}`);url.searchParams.set("metric",metrics[platform].join(","));url.searchParams.set("period","day");const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error?.message||`Meta insights request failed (${r.status})`);return NextResponse.json({success:true,platform,account:{id:c.account_id,name:c.account_name},metrics:d.data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
