import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {encryptMarketingToken,decryptMarketingToken} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function ctx(req){const user=await requireApiUser(req);const r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,r.restaurantId,"marketing");return {user,restaurantId:r.restaurantId}}
export async function GET(req){try{const {restaurantId}=await ctx(req);const {data:p}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",restaurantId).eq("plugin_code","whatsapp-marketing").maybeSingle();if(p?.enabled!==true)throw new Error("WhatsApp Marketing plugin is not active");const {data:s}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",restaurantId).eq("plugin_code","whatsapp-marketing").maybeSingle();const c=s?.config||{};let templates=[];let template_error=null;if(c.access_token&&c.phone_number_id&&c.waba_id){try{const token=decryptMarketingToken(c.access_token);const r=await fetch(`https://graph.facebook.com/${c.api_version||"v24.0"}/${c.waba_id}/message_templates?limit=100`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(r.ok&&!d.error)templates=d.data||[];else template_error=d.error?.message||`Meta API ${r.status}`}catch(e){template_error=e.message}}const {data:conn}=await supabaseCloudAdmin.from("marketing_connections").select("status,token_expires_at,last_tested_at,last_test_status,last_error").eq("restaurant_id",restaurantId).eq("platform","whatsapp").order("updated_at",{ascending:false}).limit(1).maybeSingle();return NextResponse.json({success:true,config:{phone_number_id:c.phone_number_id||"",waba_id:c.waba_id||"",api_version:c.api_version||"v24.0",has_token:Boolean(c.access_token),require_opt_in:c.require_opt_in!==false,allow_broadcasts:c.allow_broadcasts!==false,status:conn?.status||"disconnected",token_expires_at:conn?.token_expires_at||null,last_tested_at:conn?.last_tested_at||null,last_test_status:conn?.last_test_status||null,last_error:conn?.last_error||null},templates,template_error})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const {restaurantId}=await ctx(req);const {data:p}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",restaurantId).eq("plugin_code","whatsapp-marketing").maybeSingle();if(p?.enabled!==true)throw new Error("WhatsApp Marketing plugin is not active");const b=await req.json();const {data:old}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",restaurantId).eq("plugin_code","whatsapp-marketing").maybeSingle();const c={...(old?.config||{})};if(b.phone_number_id!==undefined)c.phone_number_id=String(b.phone_number_id).trim();
if(b.waba_id!==undefined)c.waba_id=String(b.waba_id).trim();if(b.api_version!==undefined)c.api_version=String(b.api_version).trim();if(b.require_opt_in!==undefined)c.require_opt_in=b.require_opt_in===true;if(b.allow_broadcasts!==undefined)c.allow_broadcasts=b.allow_broadcasts===true;if(String(b.access_token||"").trim())c.access_token=encryptMarketingToken(String(b.access_token).trim());const {error}=await supabaseCloudAdmin.from("plugin_settings").upsert({restaurant_id:restaurantId,plugin_code:"whatsapp-marketing",config:c},{onConflict:"restaurant_id,plugin_code"});if(error)throw error;await supabaseCloudAdmin.from("marketing_connections").upsert({restaurant_id:restaurantId,platform:"whatsapp",account_id:c.phone_number_id||null,account_name:"WhatsApp Marketing",status:"connected",encrypted_access_token:c.access_token||null,metadata:{source:"marketing-settings"},connected_at:new Date().toISOString()},{onConflict:"restaurant_id,platform,account_id"});return NextResponse.json({success:true})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
