// Canonical ownership map for legacy feature codes.
// Restaurant Core is intentionally preserved as the owner of its existing POS/core features.
// Every other feature resolves to exactly one owning plugin. No Restaurant Pro fallback.
export const FEATURE_PLUGIN_OWNER = Object.freeze({
  // Restaurant Core — intentionally unchanged
  "pos-core": "restaurant-core",
  "multi-terminal": "restaurant-core",
  "combos-variants": "offers",
  "takeaway": "restaurant-core",
  "delivery": "restaurant-core",
  "delivery-settlement": "restaurant-core",
  "token-management": "restaurant-core",
  "split-merge-bills": "restaurant-core",
  "table-management": "restaurant-core",
  "table-transfer": "restaurant-core",
  "payments": "restaurant-core",
  "refunds-voids": "restaurant-core",
  "discounts-tax": "restaurant-core",
  "e-bill": "restaurant-core",
  "cash-closing": "operations-hub",
  "kds": "restaurant-core",
  "kds-stations": "restaurant-core",

  // Restaurant Suite — outlet-level operational modules that already live in Suite
  "central-kitchen": "restaurant-suite",
  "inventory-advanced": "restaurant-suite",
  "recipe-bom": "restaurant-suite",
  "auto-stock-deduction": "restaurant-suite",
  "low-stock-alerts": "restaurant-suite",
  "fifo": "restaurant-suite",
  "stock-transfer": "restaurant-suite",
  "online-ordering": "restaurant-suite",
  "aggregator-menu": "restaurant-suite",
  "aggregator-runtime": "restaurant-suite",
  "online-reconciliation": "restaurant-suite",
  "order-channel-hub": "restaurant-suite",
  "restaurant-website": "restaurant-suite",
  "virtual-brands": "restaurant-suite",
  "pos-terminals": "p1-payment-terminals",
  "staff-shifts": "restaurant-suite",
  "manager-approvals": "restaurant-suite",
  "central-menu-publishing": "restaurant-suite",
  "accounting-integrations": "restaurant-suite",

  // Operations Hub — its own customer/staff/operational workspace
  "crm": "operations-hub",
  "customer-segments": "operations-hub",
  "loyalty": "operations-hub",
  "wallet": "operations-hub",
  "feedback-reviews": "operations-hub",
  "staff-attendance": "operations-hub",
  "permissions": "operations-hub",
  "expenses": "operations-hub",

  // Purchasing/Supplier domain
  "purchasing": "p1-supplier-automation",
  "purchase-manager": "p1-supplier-automation",

  // Dedicated plugins
  "reservations-pro": "reservations-pro",
  "reservations": "reservations-pro",
  "qr-ordering-pro": "qr-ordering-pro",
  "qr-menu": "qr-ordering-pro",
  "qr-print-center": "qr-print-center",
  "scan-pay": "payment-accounts",
  "website-ordering": "website-ordering",
  "captain-app": "captain-app",
  "captain-runtime": "captain-app",
  "smart-notifications": "smart-notifications",
  "calling-device": "calling-device",
  "calling-runtime": "calling-device",
  "self-service-kiosk": "p2-advanced-kiosk",
  "kiosk-runtime": "p2-advanced-kiosk",
  "kiosk-multilanguage": "p2-advanced-kiosk",
  "digital-display": "p2-customer-display",
  "token-display": "p2-customer-display",
  "scan-order-runtime": "qr-ordering-pro",
  "theme-branding": "theme-branding",
  "restaurant-settings": "restaurant-settings",
  "offers": "offers",
  "thermal-printing": "thermal-printing",
  "a4-invoice": "a4-invoice",
  "hardware-print-queue": "hardware-print-queue",
  "payment-accounts": "payment-accounts",
  "payment-gateways": "cashfree-payment-gateway",
  "cash-shift": "operations-hub",
  "whatsapp-invoice": "whatsapp-invoice",
  "whatsapp": "whatsapp-invoice",
  "whatsapp-marketing": "whatsapp-marketing",
  "swiggy-integration": "swiggy-integration",
  "zomato-integration": "zomato-integration",
  "facebook-integration": "facebook-integration",
  "instagram-integration": "instagram-integration",

  // P1 Marketing owns campaign orchestration; provider integrations remain independent.
  "campaigns": "p1-marketing-hub",
  "sms-marketing": "p1-marketing-hub",
  "message-center": "p1-marketing-hub",

  // P1 Reporting owns reporting/analytics. It is no longer surfaced under Marketing.
  "analytics": "p1-advanced-reporting",
  "dynamic-reports": "p1-advanced-reporting",
  "profit-food-cost": "p1-advanced-reporting",
  "tax-reports": "p1-advanced-reporting",
  "staff-reports": "p1-advanced-reporting",
  "scheduled-reports": "p1-advanced-reporting",

  // P1/P2 canonical plugins own their entire internal feature surface.
  "p1-enterprise-hq": "p1-enterprise-hq",
  "multi-branch": "p1-enterprise-hq",
  "branch-menu": "p1-enterprise-hq",
  "forecasting": "p2-ai-intelligence",
  "p1-payment-terminals": "p1-payment-terminals",
  "p1-supplier-automation": "p1-supplier-automation",
  "p1-supplier-portal": "p1-supplier-portal",
  "p1-marketing-hub": "p1-marketing-hub",
  "p1-advanced-reporting": "p1-advanced-reporting",
  "p0-system-reliability": "p0-system-reliability",
  "p2-call-center": "p2-call-center",
  "p2-banquet-events": "p2-banquet-events",
  "p2-advanced-kiosk": "p2-advanced-kiosk",
  "p2-customer-display": "p2-customer-display",
  "p2-device-hq": "p2-device-hq",
  "p2-ai-intelligence": "p2-ai-intelligence",
});

export function pluginOwnerForFeature(code) {
  return FEATURE_PLUGIN_OWNER[code] || code;
}
