import crypto from "crypto"
import { NextResponse } from "next/server"
import { requireApiUser } from "@/lib/serverAuth"
import { supabaseCloudAdmin } from "@/lib/supabaseCloudServer"
export const runtime = "nodejs"
const BUCKET = "calling-voice-media"
const MAX_BYTES = 15 * 1024 * 1024
const ALLOWED = new Set(["audio/mpeg","audio/mp3","audio/wav","audio/x-wav","audio/ogg","audio/webm","audio/mp4","audio/aac"])
async function getProfile(userId){const {data}=await supabaseCloudAdmin.from("profiles").select("id,role,restaurant_id").eq("id",userId).maybeSingle();return data}
export async function POST(req){try{const user=await requireApiUser(req);const profile=await getProfile(user.id);if(!profile||!["admin","super_admin"].includes(profile.role))throw new Error("Admin access required");const form=await req.formData();const file=form.get("file");const restaurantId=String(form.get("restaurant_id")||profile.restaurant_id||"").trim();const eventKey=String(form.get("event_key")||"custom").trim().replace(/[^a-z0-9_-]/gi,"-").slice(0,60);if(!restaurantId||!file||typeof file.arrayBuffer!=="function")throw new Error("Voice audio file is required");if(profile.role!=="super_admin"&&profile.restaurant_id!==restaurantId)throw new Error("Restaurant access denied");const {data:pluginRows}=await supabaseCloudAdmin.from("restaurant_plugins").select("plugin_code,enabled").eq("restaurant_id",restaurantId).in("plugin_code",["calling-device","payment-accounts"]);const callingEnabled=pluginRows?.some(x=>x.plugin_code==="calling-device"&&x.enabled===true);const paymentEnabled=pluginRows?.some(x=>x.plugin_code==="payment-accounts"&&x.enabled===true);if(!callingEnabled&&!paymentEnabled)throw new Error("Calling Device or Merchant Payments & Voice plugin is not enabled");if(!callingEnabled&&eventKey!=="payment_received")throw new Error("Payment voice upload is only available without Calling Device for the payment_received event");const type=String(file.type||"audio/mpeg").toLowerCase();if(!type.startsWith("audio/")||(!ALLOWED.has(type)&&!type.includes("mpeg")))throw new Error("Only MP3, WAV, OGG, WEBM, MP4 or AAC audio files are supported");if(Number(file.size||0)>MAX_BYTES)throw new Error("Voice audio must be 15 MB or smaller");const ext=(String(file.name||"voice.mp3").split(".").pop()||"mp3").replace(/[^a-z0-9]/gi,"").toLowerCase()||"mp3";const path=`${restaurantId}/${eventKey}-${crypto.randomUUID()}.${ext}`;const bytes=Buffer.from(await file.arrayBuffer());const {error}=await supabaseCloudAdmin.storage.from(BUCKET).upload(path,bytes,{contentType:type,upsert:false});if(error)throw error;const {data}=supabaseCloudAdmin.storage.from(BUCKET).getPublicUrl(path);return NextResponse.json({success:true,url:data.publicUrl,path,name:file.name||path})}catch(e){const message=e?.message||"Unable to upload calling voice";return NextResponse.json({success:false,error:message},{status:/access|admin|authorized|authentication/i.test(message)?403:400})}}
export async function DELETE(req){try{const user=await requireApiUser(req);const profile=await getProfile(user.id);if(!profile||!["admin","super_admin"].includes(profile.role))throw new Error("Admin access required");const body=await req.json().catch(()=>({}));const restaurantId=String(body.restaurant_id||profile.restaurant_id||"").trim();const path=String(body.path||"").trim();if(!restaurantId||!path)throw new Error("restaurant_id and path are required");if(profile.role!=="super_admin"&&profile.restaurant_id!==restaurantId)throw new Error("Restaurant access denied");if(!path.startsWith(`${restaurantId}/`))throw new Error("Invalid voice asset path");const {error}=await supabaseCloudAdmin.storage.from(BUCKET).remove([path]);if(error)throw error;return NextResponse.json({success:true})}catch(e){const message=e?.message||"Unable to delete calling voice";return NextResponse.json({success:false,error:message},{status:/access|admin|authorized|authentication/i.test(message)?403:400})}}
