"use client"
import {useEffect,useState} from "react"
import {supabaseCloud} from "@/lib/supabaseCloud"
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`
const card={background:"var(--surface)",border:"1px solid var(--border)",borderRadius:16,padding:18}
const input={width:"100%",padding:10,borderRadius:9,border:"1px solid var(--border)",background:"var(--background)",color:"inherit",boxSizing:"border-box"}
export default function InventoryCosting(){const [rid,setRid]=useState(null),[from,setFrom]=useState(new Date().toISOString().slice(0,8)+"01"),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[d,setD]=useState(null),[items,setItems]=useState([]),[sel,setSel]=useState(""),[recipe,setRecipe]=useState(null),[msg,setMsg]=useState("")
useEffect(()=>{(async()=>{const {data:u}=await supabaseCloud.auth.getUser();if(!u?.user){setMsg("Login required");return}const {data:p}=await supabaseCloud.from("profiles").select("restaurant_id").eq("id",u.user.id).maybeSingle();if(!p?.restaurant_id){setMsg("Restaurant not linked");return}setRid(p.restaurant_id);const {data:i}=await supabaseCloud.from("inventory").select("id,name,quantity,unit,cost_price,costing_method").eq("restaurant_id",p.restaurant_id).order("name");setItems(i||[])})()()},[])
const load=async()=>{if(!rid)return;setMsg("");const {data,e}=await supabaseCloud.rpc("p1_3_cogs_dashboard",{p_restaurant_id:rid,p_from:from,p_to:to});if(e)setMsg(e.message);else setD(data)}
const cost=async()=>{if(!rid||!sel)return;const {data,e}=await supabaseCloud.rpc("p1_3_recipe_cost",{p_restaurant_id:rid,p_menu_item_id:sel});if(e)setMsg(e.message);else setRecipe(data)}
const close=async()=>{if(!rid)return;const {data,e}=await supabaseCloud.rpc("p1_3_close_inventory_period",{p_restaurant_id:rid,p_period_start:from,p_period_end:to});if(e)setMsg(e.message);else setMsg(`Period closed • Closing valuation ${money(data?.closing_value)}`)}
return <main style={{padding:20,maxWidth:1450,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><h1 style={{margin:0}}>Inventory Costing & COGS</h1><p style={{opacity:.7}}>FIFO • Weighted Average • Recipe Cost • Variance • Valuation • Period Close</p></div><a href="/dashboard/inventory/pro" style={{...card,padding:"9px 13px",textDecoration:"none"}}>Inventory Pro</a></div>
{msg&&<div style={{...card,margin:"14px 0",borderColor:"#b91c1c"}}>{msg}</div>}
<div style={{...card,marginTop:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><label>From<input style={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input style={input} type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load} style={{...input,alignSelf:"end",cursor:"pointer"}}>Refresh COGS</button><button onClick={close} style={{...input,alignSelf:"end",cursor:"pointer"}}>Close Period</button></div>
{d&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginTop:14}}>{[["Revenue",money(d.revenue)],["Actual COGS",money(d.actual_cogs)],["Theoretical COGS",money(d.theoretical_cogs)],["Variance",money(d.variance)],["Waste",money(d.waste)],["Waste %",`${Number(d.waste_percent||0).toFixed(2)}%`],["Food Cost %",`${Number(d.food_cost_percent||0).toFixed(2)}%`],["Stock / AOV",money(d.aov)]].map(([a,b])=><div style={card} key={a}><div style={{opacity:.65}}>{a}</div><strong style={{fontSize:22}}>{b}</strong></div>)}</div>}
<div style={{display:"grid",gridTemplateColumns:"minmax(280px,430px) 1fr",gap:14,marginTop:14}}><div style={card}><h3>Inventory valuation / costing method</h3>{items.map(x=><div key={x.id} style={{padding:"10px 0",borderBottom:"1px solid var(--border)"}}><strong>{x.name}</strong><div style={{opacity:.7}}>{x.quantity} {x.unit} • {money(x.cost_price)} • {(x.costing_method||"fifo").toUpperCase()}</div></div>)}</div><div style={card}><h3>Recipe costing</h3><input style={input} placeholder="Menu item UUID" value={sel} onChange={e=>setSel(e.target.value)}/><button onClick={cost} style={{...input,marginTop:8,cursor:"pointer"}}>Calculate recipe cost</button>{recipe&&<pre style={{whiteSpace:"pre-wrap",overflowX:"auto"}}>{JSON.stringify(recipe,null,2)}</pre>}</div></div></main>}
