import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
export async function GET(req){try{await sa(req);const {data,error}=await supabaseCloudAdmin.from("platform_marketing_leads").select("*").order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({success:true,leads:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:403})}}
export async function POST(req){try{const u=await sa(req),b=await req.json();const {data,error}=await supabaseCloudAdmin.from("platform_marketing_leads").insert({name:String(b.name||""),phone:b.phone||null,email:b.email||null,source:String(b.source||"manual"),campaign_id:b.campaign_id||null,status:["new","contacted","demo","trial","subscribed","lost"].includes(b.status)?b.status:"new",notes:b.notes||null,restaurant_id:b.restaurant_id||null,assigned_to:b.assigned_to||null,last_contacted_at:b.last_contacted_at||null,next_followup_at:b.next_followup_at||null}).select("*").single();if(error)throw error;await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"lead_created",entity_type:"lead",entity_id:data.id,metadata:{source:data.source}});return NextResponse.json({success:true,lead:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function PATCH(req){try{const u=await sa(req),b=await req.json();if(!b.id)throw new Error("Lead id is required");const patch={};for(const k of ["name","phone","email","source","campaign_id","notes","restaurant_id","assigned_to","last_contacted_at","next_followup_at"]){if(b[k]!==undefined)patch[k]=b[k]||null}if(b.status!==undefined){const s=String(b.status);if(!["new","contacted","demo","trial","subscribed","lost"].includes(s))throw new Error("Invalid lead status");patch.status=s;if(s!=="new"&&!patch.last_contacted_at)patch.last_contacted_at=new Date().toISOString()}const {data,error}=await supabaseCloudAdmin.from("platform_marketing_leads").update(patch).eq("id",b.id).select("*").single();if(error)throw error;await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"lead_updated",entity_type:"lead",entity_id:b.id,metadata:{status:data.status}});return NextResponse.json({success:true,lead:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
