"use client"
import {useEffect,useState} from "react"
import {supabaseCloud} from "@/lib/supabaseCloud"
const css=`.ep{min-height:100vh;padding:24px clamp(12px,3vw,40px) 60px;background:radial-gradient(circle at 80% -10%,rgba(211,169,63,.10),transparent 30%),linear-gradient(145deg,#071312,#081715 55%,#06100f);color:#f5f1e5}.ep-shell{max-width:1450px;margin:auto}.ep-hero,.ep-card{border:1px solid rgba(211,169,63,.24);border-radius:20px;background:linear-gradient(145deg,rgba(16,32,29,.97),rgba(8,20,18,.97));box-shadow:0 15px 38px rgba(0,0,0,.2)}.ep-hero{padding:24px;margin-bottom:16px}.ep-k{font-size:11px;font-weight:900;letter-spacing:2px;color:#f0cf72}.ep-h{font-size:clamp(25px,3vw,38px);margin:7px 0;font-weight:900}.ep-p{color:#9baaa5;margin:0}.ep-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin-bottom:16px}.ep-stat{padding:17px;border:1px solid rgba(211,169,63,.24);border-radius:17px;background:rgba(10,23,20,.92)}.ep-label{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#9baaa5}.ep-num{font-size:28px;font-weight:900;margin-top:7px}.ep-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}.ep-card{padding:18px}.ep-card h2{margin:0 0 13px;font-size:16px}.ep-list{list-style:none;padding:0;margin:0}.ep-list li{padding:11px 0;border-bottom:1px solid rgba(255,255,255,.07);display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.ep-list li:last-child{border-bottom:0}.ep-muted{color:#9baaa5}.ep-error{border:1px solid rgba(227,107,107,.38);background:rgba(110,30,30,.18);color:#ffb1b1;border-radius:14px;padding:14px}`
const cardClass="ep-card"
export default function EnterprisePage(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 useEffect(()=>{(async()=>{try{const {data:u}=await supabaseCloud.auth.getUser();if(!u?.user)throw Error("Please sign in again.");const {data:s}=await supabaseCloud.auth.getSession();const token=s?.session?.access_token;if(!token)throw Error("Session token unavailable.");const {data:members,error:me}=await supabaseCloud.from("enterprise_members").select("enterprise_id").eq("user_id",u.user.id).limit(1);if(me)throw me;if(!members?.[0]){setData({empty:true});return}const r=await fetch(`/api/enterprise/summary?enterprise_id=${encodeURIComponent(members[0].enterprise_id)}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const p=await r.json();if(!r.ok||!p.success)throw Error(p.error||"Unable to load enterprise");setData(p)}catch(e){setError(e.message||"Unable to load enterprise")}finally{setLoading(false)}})()},[])
 if(loading)return <><style>{css}</style><main className="ep"><div className="ep-shell"><div className={cardClass} style={{padding:22}}>Loading Enterprise Control Center…</div></div></main></>
 if(error)return <><style>{css}</style><main className="ep"><div className="ep-shell"><div className="ep-error">{error}</div></div></main></>
 if(data?.empty)return <><style>{css}</style><main className="ep"><div className="ep-shell"><div className="ep-hero"><div className="ep-k">ANAIRA · ENTERPRISE</div><h1 className="ep-h">Enterprise Control Center</h1><p className="ep-p">Your account is not linked to an enterprise group yet.</p></div></div></main></>
 const outlets=data.outlets||[],members=data.members||[],catalog=data.catalog||[],transfers=data.transfers||[],devices=data.devices||[]
 return <><style>{css}</style><main className="ep"><div className="ep-shell"><header className="ep-hero"><div className="ep-k">ANAIRA · ENTERPRISE CONTROL</div><h1 className="ep-h">{data.enterprise?.name||"Enterprise Control Center"}</h1><p className="ep-p">Multi-outlet control, central menu, inventory transfers, devices and governance.</p></header><section className="ep-grid">{[["Outlets",outlets.length],["Members",members.length],["Central Menu",catalog.length],["Transfers",transfers.length],["Devices",devices.length]].map(([a,b])=><div className="ep-stat" key={a}><div className="ep-label">{a}</div><div className="ep-num">{b}</div></div>)}</section><section className="ep-cards"><div className={cardClass}><h2>Outlets</h2>{outlets.length?<ul className="ep-list">{outlets.map(o=><li key={o.id}><b>{o.outlet_name||o.restaurant_id}</b><span className="ep-muted">{o.outlet_code||"—"}</span></li>)}</ul>:<p className="ep-muted">No outlets linked yet.</p>}</div><div className={cardClass}><h2>Enterprise Roles</h2>{members.length?<ul className="ep-list">{members.map(m=><li key={m.id}><b>{m.role}</b><span className="ep-muted">{m.user_id}</span></li>)}</ul>:<p className="ep-muted">No members.</p>}</div><div className={cardClass}><h2>Central Menu</h2>{catalog.length?<ul className="ep-list">{catalog.slice(0,12).map(c=><li key={c.id}><b>{c.name}</b><span className="ep-muted">₹{Number(c.base_price||0).toLocaleString("en-IN")}</span></li>)}</ul>:<p className="ep-muted">No central menu items yet.</p>}</div><div className={cardClass}><h2>Inventory Transfers</h2>{transfers.length?<ul className="ep-list">{transfers.slice(0,12).map(t=><li key={t.id}><b>{t.item_name} × {t.quantity}</b><span className="ep-muted">{t.status}</span></li>)}</ul>:<p className="ep-muted">No active transfers.</p>}</div><div className={cardClass}><h2>Device Management</h2>{devices.length?<ul className="ep-list">{devices.map(d=><li key={d.id}><b>{d.device_name||d.device_key}</b><span className="ep-muted">{d.device_type} · {d.status}</span></li>)}</ul>:<p className="ep-muted">No devices registered.</p>}</div></section></div></main></>
}
