import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
export async function GET(req){try{await sa(req);const {data,error}=await supabaseCloudAdmin.from("platform_marketing_campaigns").select("*").order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({success:true,campaigns:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:403})}}
export async function POST(req){try{const u=await sa(req),b=await req.json();const name=String(b.name||"").trim();if(!name)throw new Error("Campaign name is required");const channels=Array.isArray(b.channels)?b.channels.filter(x=>["facebook","instagram","whatsapp"].includes(x)):[];const {data,error}=await supabaseCloudAdmin.from("platform_marketing_campaigns").insert({name,objective:String(b.objective||"saas-acquisition"),status:["draft","active","paused","completed"].includes(b.status)?b.status:"draft",budget:Number(b.budget||0),start_at:b.start_at||null,end_at:b.end_at||null,channels,audience_type:String(b.audience_type||"all"),created_by:u.id}).select("*").single();if(error)throw error;await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"campaign_created",entity_type:"campaign",entity_id:data.id,metadata:{name,channels}});return NextResponse.json({success:true,campaign:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function PATCH(req){try{const u=await sa(req),b=await req.json();if(!b.id)throw new Error("Campaign id is required");const patch={};for(const k of ["name","objective","budget","actual_spend","start_at","end_at","audience_type","landing_url"]){if(b[k]!==undefined)patch[k]=["budget","actual_spend"].includes(k)?Math.max(0,Number(b[k]||0)):b[k]}if(b.channels!==undefined)patch.channels=Array.isArray(b.channels)?b.channels.filter(x=>["facebook","instagram","whatsapp"].includes(x)):[];if(b.status!==undefined){const s=String(b.status);if(!["draft","active","paused","completed"].includes(s))throw new Error("Invalid campaign status");patch.status=s}const {data,error}=await supabaseCloudAdmin.from("platform_marketing_campaigns").update(patch).eq("id",b.id).select("*").single();if(error)throw error;await supabaseCloudAdmin.from("marketing_audit_logs").insert({scope:"platform",actor_id:u.id,action:"campaign_updated",entity_type:"campaign",entity_id:b.id,metadata:{status:data.status}});return NextResponse.json({success:true,campaign:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
