import { requireFeature } from "@/lib/featureGateServer"
import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
async function ctx(req){const user=await requireApiUser(req);const {restaurantId}=await resolveRestaurantForUser(user);if(!restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,restaurantId,"restaurant-core");return {user,restaurantId}}
export async function GET(req){try{const {restaurantId}=await ctx(req);await requireFeature(restaurantId, "p2-advanced-kiosk");const {data,error}=await supabaseCloudAdmin.from("p2_3_kiosks").select("*").eq("restaurant_id",restaurantId).order("name");if(error)throw error;return NextResponse.json({success:true,kiosks:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const {restaurantId}=await ctx(req);await requireFeature(restaurantId, "p2-advanced-kiosk");const b=await req.json();const action=String(b.action||"");if(action==="register"){const code=String(b.kiosk_code||"").trim().toUpperCase();if(!code)throw new Error("Kiosk code is required");const {data,error}=await supabaseCloudAdmin.rpc("p2_3_register_kiosk",{p_restaurant_id:restaurantId,p_kiosk_code:code,p_name:String(b.name||code),p_device_id:b.device_id||null,p_version:b.version||null});if(error)throw error;return NextResponse.json({success:true,kiosk:data})}if(action==="update"){const id=String(b.id||"");if(!id)throw new Error("Kiosk ID required");const patch={name:String(b.name||"Kiosk"),status:["active","inactive","offline","maintenance"].includes(b.status)?b.status:"active",version:b.version||null,config:b.config||{},branding:b.branding||{},printer_config:b.printer_config||{},payment_config:b.payment_config||{},token_config:b.token_config||{},updated_at:new Date().toISOString()};const {data,error}=await supabaseCloudAdmin.from("p2_3_kiosks").update(patch).eq("id",id).eq("restaurant_id",restaurantId).select().single();if(error)throw error;return NextResponse.json({success:true,kiosk:data})}if(action==="heartbeat"){const {data,error}=await supabaseCloudAdmin.rpc("p2_3_heartbeat_kiosk",{p_restaurant_id:restaurantId,p_kiosk_id:b.id,p_version:b.version||null,p_menu_version:b.menu_version||null});if(error)throw error;return NextResponse.json({success:true,data})}throw new Error("Unsupported action")}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
