import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
import {encryptMarketingToken,decryptMarketingToken,metaJson} from "@/lib/marketingMeta"
export const runtime="nodejs"
async function ctx(req){const user=await requireApiUser(req);const r=await resolveRestaurantForUser(user);if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(user,r.restaurantId,"marketing");return {user,restaurantId:r.restaurantId}}
export async function GET(req){try{const {restaurantId}=await ctx(req);const {data,error}=await supabaseCloudAdmin.from("marketing_connections").select("id,platform,account_id,account_name,profile_image_url,status,metadata,token_expires_at,connected_at,updated_at").eq("restaurant_id",restaurantId).order("updated_at",{ascending:false});if(error)throw error;return NextResponse.json({success:true,connections:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const {restaurantId}=await ctx(req);const b=await req.json();const platform=String(b.platform||"").toLowerCase();if(!["facebook","instagram","whatsapp"].includes(platform))throw new Error("Unsupported platform");const code=platform==="whatsapp"?"whatsapp-marketing":`${platform}-integration`;const {data:plugin}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",restaurantId).eq("plugin_code",code).maybeSingle();if(plugin?.enabled!==true)throw new Error(`${platform} marketing plugin is not active`);const token=String(b.access_token||"");const {data:old}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",restaurantId).eq("plugin_code",code).maybeSingle();const oldCfg=old?.config||{};const config={...oldCfg};for(const k of ["account_id","account_name","profile_image_url","phone_number_id","base_url","api_version"]){if(b[k]!==undefined)config[k]=b[k]};if(token)config.access_token=encryptMarketingToken(token);const {error}=await supabaseCloudAdmin.from("plugin_settings").upsert({restaurant_id:restaurantId,plugin_code:code,config},{onConflict:"restaurant_id,plugin_code"});if(error)throw error;const {error:ce}=await supabaseCloudAdmin.from("marketing_connections").upsert({restaurant_id:restaurantId,platform,account_id:b.account_id||b.phone_number_id||null,account_name:b.account_name||null,profile_image_url:b.profile_image_url||null,status:"connected",encrypted_access_token:token?encryptMarketingToken(token):undefined,connected_at:new Date().toISOString(),metadata:{source:"manual"}},{onConflict:"restaurant_id,platform,account_id"});if(ce)throw ce;return NextResponse.json({success:true})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function DELETE(req){try{const {user,restaurantId}=await ctx(req);const platform=String(new URL(req.url).searchParams.get("platform")||"").toLowerCase();if(!["facebook","instagram","whatsapp"].includes(platform))throw new Error("Unsupported platform");const {data:rows}=await supabaseCloudAdmin.from("marketing_connections").select("id,account_id").eq("restaurant_id",restaurantId).eq("platform",platform);await supabaseCloudAdmin.from("marketing_connections").update({status:"disconnected",encrypted_access_token:null,token_expires_at:null,metadata:{source:"disconnect",disconnected_at:new Date().toISOString()}}).eq("restaurant_id",restaurantId).eq("platform",platform);const code=platform==="whatsapp"?"whatsapp-marketing":`${platform}-integration`;const {data:old}=await supabaseCloudAdmin.from("plugin_settings").select("config").eq("restaurant_id",restaurantId).eq("plugin_code",code).maybeSingle();if(old){const cfg={...(old.config||{})};delete cfg.access_token;delete cfg.account_id;delete cfg.account_name;delete cfg.profile_image_url;delete cfg.meta_pages;await supabaseCloudAdmin.from("plugin_settings").update({config:cfg}).eq("restaurant_id",restaurantId).eq("plugin_code",code)}await supabaseCloudAdmin.from("marketing_audit_logs").insert({restaurant_id:restaurantId,actor_id:user.id,action:"marketing_disconnect",platform,entity_type:"connection",metadata:{removed:rows?.length||0}});return NextResponse.json({success:true,removed:rows?.length||0})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
