'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'

export default function AdvancedKDS(){
 const [tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const load=useCallback(async()=>{try{setError('');const r=await fetch('/api/kds/advanced',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Failed');setTickets(j.tickets||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load])
 const update=async(ticket,status)=>{try{setBusy(ticket.id);const r=await fetch('/api/kds/advanced',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket_id:ticket.id,status})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Update failed');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const counts=useMemo(()=>Object.fromEntries(['new','accepted','preparing','ready'].map(s=>[s,tickets.filter(x=>x.status===s).length])),[tickets])
 return <main className="kds-advanced-page"><div className="kds-head"><div><h1>Advanced KDS</h1><p>Live kitchen queue, stations, priorities and SLA tracking.</p></div><button onClick={load}>Refresh</button></div>{error&&<div className="kds-error">{error}</div>}{loading?<div>Loading kitchen queue…</div>:<><div className="kds-summary">{Object.entries(counts).map(([k,v])=><div key={k}><b>{v}</b><span>{k}</span></div>)}</div><div className="kds-board">{['new','accepted','preparing','ready'].map(status=><section key={status} className="kds-column"><h2>{status.toUpperCase()} <small>{counts[status]}</small></h2>{tickets.filter(x=>x.status===status).map(t=><article className="kds-ticket" key={t.id}><div className="kds-ticket-top"><strong>#{t.order_number||t.order_id?.slice(0,8)}</strong><span>{t.priority}</span></div><h3>{t.item_name}</h3><p>Qty {t.quantity} · {t.station_name||'Unassigned station'}</p>{t.cooking_request&&<p>{t.cooking_request}</p>}<small>{t.sla_due_at?`SLA ${new Date(t.sla_due_at).toLocaleTimeString()}`:''}</small><div className="kds-actions">{status==='new'&&<button disabled={busy===t.id} onClick={()=>update(t,'accepted')}>Accept</button>}{status==='accepted'&&<button disabled={busy===t.id} onClick={()=>update(t,'preparing')}>Start</button>}{status==='preparing'&&<button disabled={busy===t.id} onClick={()=>update(t,'ready')}>Ready</button>}{status==='ready'&&<button disabled={busy===t.id} onClick={()=>update(t,'served')}>Served</button>}</div></article>)}</section>)}</div></>}</main>
}
