import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireStaffPermission} from "@/lib/serverStaffPermissions"
import {resolveRestaurantForUser} from "@/lib/restaurantResolver"
export const runtime="nodejs"
async function rid(req){const u=await requireApiUser(req),r=await resolveRestaurantForUser(u);if(!r.restaurantId)throw new Error("Restaurant not found");await requireStaffPermission(u,r.restaurantId,"marketing");const {data:rows}=await supabaseCloudAdmin.from("restaurant_plugins").select("enabled").eq("restaurant_id",r.restaurantId).in("plugin_code",["facebook-integration","instagram-integration","whatsapp-marketing"]);if(!(rows||[]).some(x=>x.enabled===true))throw new Error("Marketing is not active for this restaurant");return r.restaurantId}
export async function GET(req){try{const id=await rid(req);const {data,error}=await supabaseCloudAdmin.from("marketing_audience_members").select("*").eq("restaurant_id",id).order("created_at",{ascending:false}).limit(1000);if(error)throw error;return NextResponse.json({success:true,members:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function POST(req){try{const id=await rid(req),b=await req.json();const channel=String(b.channel||"").toLowerCase(),address=String(b.address||"").trim();if(!["whatsapp","facebook","instagram","email"].includes(channel)||!address)throw new Error("Channel and address are required");const {data,error}=await supabaseCloudAdmin.from("marketing_audience_members").upsert({restaurant_id:id,channel,address,lead_id:b.lead_id||null,customer_id:b.customer_id||null,consent:b.consent===true,consent_at:b.consent===true?new Date().toISOString():null,metadata:b.metadata||{}},{onConflict:"restaurant_id,channel,address"}).select("*").single();if(error)throw error;return NextResponse.json({success:true,member:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
export async function PATCH(req){try{const id=await rid(req),b=await req.json();if(!b.id)throw new Error("Member id is required");const patch={};if(b.consent!==undefined){patch.consent=b.consent===true;patch.consent_at=patch.consent?new Date().toISOString():null}if(b.unsubscribed!==undefined)patch.unsubscribed_at=b.unsubscribed?new Date().toISOString():null;const {data,error}=await supabaseCloudAdmin.from("marketing_audience_members").update(patch).eq("id",b.id).eq("restaurant_id",id).select("*").single();if(error)throw error;return NextResponse.json({success:true,member:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
