"use client"
import Link from "next/link"
import PublicMarketingChrome from "@/components/PublicMarketingChrome"

const plans=[
 {key:"starter",name:"Starter",price:"₹999",tag:"For getting started",features:["Restaurant POS","Orders, tables & billing","Advanced QR Ordering","Core restaurant operations","Basic analytics"]},
 {key:"professional",name:"Professional",price:"₹1,999",tag:"Most popular",popular:true,features:["Everything in Starter","WhatsApp","Operations Hub","Advanced Reservations","Offers & Combos","Growth-ready workflows"]},
 {key:"enterprise",name:"Enterprise",price:"₹3,999",tag:"For complete operations",features:["Everything in Professional","All catalog plugins","All optional features","Advanced operations","Complete growth stack"]},
]
export default function Pricing(){return <PublicMarketingChrome><main><style jsx>{`
.hero{padding:75px 0 45px;text-align:center;background:radial-gradient(circle at 50% 0,rgba(245,183,46,.14),transparent 35%)}.hero h1{font-size:clamp(40px,5vw,62px);line-height:1;letter-spacing:-.055em;margin:15px 0}.gold{color:var(--gold)}.hero p{max-width:680px;margin:auto;color:var(--muted);line-height:1.75}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:28px 0 60px}.plan{position:relative;padding:26px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,#0c1726,#07101b)}.plan.popular{border-color:rgba(245,183,46,.55);box-shadow:0 22px 60px rgba(245,183,46,.09)}.badge{position:absolute;right:16px;top:16px;padding:6px 9px;border-radius:999px;background:rgba(245,183,46,.13);color:var(--gold);font-size:9px;font-weight:850}.plan h2{margin:0;font-size:22px}.tag{color:var(--muted);font-size:11px;margin-top:6px}.price{font-size:37px;font-weight:900;letter-spacing:-.04em;margin:23px 0 3px}.price small{font-size:11px;color:var(--muted);font-weight:600}.plan ul{padding:0;margin:22px 0;list-style:none}.plan li{padding:9px 0;border-top:1px solid rgba(255,255,255,.07);color:#cbd5e1;font-size:12px}.plan li:before{content:"✓";color:var(--green);font-weight:900;margin-right:8px}.cta{display:block;text-align:center;text-decoration:none;padding:13px;border-radius:11px;background:linear-gradient(135deg,var(--gold),var(--gold2));color:#17110a;font-size:12px;font-weight:900}.section{padding:20px 0 70px}.section h2{font-size:30px;letter-spacing:-.04em}.matrix{width:100%;border-collapse:collapse;margin-top:20px}.matrix th,.matrix td{text-align:left;padding:14px;border-bottom:1px solid var(--line);font-size:12px}.matrix th{color:#fff}.matrix td{color:var(--muted)}.yes{color:var(--green)!important}.note{padding:20px;border:1px solid var(--line);border-radius:16px;background:#09131f;color:var(--muted);font-size:12px;line-height:1.7}@media(max-width:850px){.plans{grid-template-columns:1fr}.plan.popular{transform:none}}
`}</style><section className="hero"><div className="amContainer"><div style={{color:"var(--gold)",fontSize:11,fontWeight:850,letterSpacing:'.13em'}}>SIMPLE SAAS PRICING</div><h1>Choose the right plan for your <span className="gold">restaurant.</span></h1><p>Start with the core restaurant workflow, then unlock the tools your team needs for operations, customer engagement and growth.</p><div style={{display:'flex',justifyContent:'center',gap:10,flexWrap:'wrap',marginTop:22}}><Link className="cta" style={{display:'inline-block',padding:'11px 16px'}} href="/login">Existing Customer · Sign In</Link><Link className="cta" style={{display:'inline-block',padding:'11px 16px'}} href="/contact">Talk to Anaira →</Link></div></div></section><section className="amContainer"><div className="plans">{plans.map(p=><article className={`plan ${p.popular?'popular':''}`} key={p.key}>{p.popular&&<span className="badge">MOST POPULAR</span>}<h2>{p.name}</h2><div className="tag">{p.tag}</div><div className="price">{p.price}<small>/month</small></div><ul>{p.features.map(x=><li key={x}>{x}</li>)}</ul><Link className="cta" href={`/contact?plan=${p.key}`}>{p.key==='enterprise'?'Talk to Sales →':'Request a Demo →'}</Link></article>)}</div><div className="section"><h2>Plan comparison</h2><table className="matrix"><thead><tr><th>Capability</th><th>Starter</th><th>Professional</th><th>Enterprise</th></tr></thead><tbody>{[["Restaurant POS","✓","✓","✓"],["Advanced QR Ordering","✓","✓","✓"],["WhatsApp","—","✓","✓"],["Operations Hub","—","✓","✓"],["Reservations","—","✓","✓"],["Offers & Combos","—","✓","✓"],["All optional plugins","—","Add-on","✓"],["Growth & marketing stack","Core","Advanced","Complete"]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i} className={c==='✓'?'yes':''}>{c}</td>)}</tr>)}</tbody></table><div className="note" style={{marginTop:20}}>Pricing shown here is the current Anaira public plan structure. Plugin availability can depend on the restaurant's enabled feature configuration.</div></div></section></main></PublicMarketingChrome>}
