"use client"
import {useEffect,useState} from "react"
import {supabaseCloud} from "@/lib/supabaseCloud"
const tabs=[['purchase','🛒','Purchase'],['loyalty','⭐','Loyalty'],['kiosk','🖥️','Kiosk / QR'],['kitchen','👨‍🍳','Central Kitchen'],['online','🌐','Online Channels'],['calling','🔔','Calling'],['captain','📱','Captain'],['inventory','📦','Inventory'],['reports','📊','Audit / Reports']]
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
export default function Page(){
 const[rid,setRid]=useState(''),[tab,setTab]=useState('purchase'),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[d,setD]=useState({})
 const[supplier,setSupplier]=useState({name:'',phone:''}),[purchase,setPurchase]=useState({invoice_number:'',total:''}),[reward,setReward]=useState({name:'',points_cost:100,reward_type:'discount',reward_value:50}),[kiosk,setKiosk]=useState({name:'',kiosk_code:''}),[kitchen,setKitchen]=useState({name:'',code:'',address:''}),[channel,setChannel]=useState({channel_code:'zomato',channel_name:'Zomato'}),[recon,setRecon]=useState({external_order_id:'',gross_amount:'',commission:'',payout_amount:''}),[device,setDevice]=useState({name:'',device_code:'',location:''})
 useEffect(()=>{init()},[])
 async function init(){const{data:a}=await supabaseCloud.auth.getUser();if(!a?.user)return setLoading(false);const{data:p}=await supabaseCloud.from('profiles').select('restaurant_id').eq('id',a.user.id).maybeSingle();if(!p?.restaurant_id)return setLoading(false);setRid(p.restaurant_id);load(p.restaurant_id)}
 async function load(id=rid){if(!id)return;const q=await Promise.all([
  supabaseCloud.from('restaurant_suppliers').select('*').eq('restaurant_id',id).order('name'),supabaseCloud.from('restaurant_purchases').select('*').eq('restaurant_id',id).order('created_at',{ascending:false}).limit(30),supabaseCloud.from('loyalty_rewards').select('*').eq('restaurant_id',id).order('created_at',{ascending:false}),supabaseCloud.from('self_service_kiosks').select('*').eq('restaurant_id',id).order('name'),supabaseCloud.from('central_kitchens').select('*').eq('restaurant_id',id).order('name'),supabaseCloud.from('online_channels').select('*').eq('restaurant_id',id).order('channel_name'),supabaseCloud.from('online_order_reconciliations').select('*').eq('restaurant_id',id).order('created_at',{ascending:false}).limit(30),supabaseCloud.from('calling_devices').select('*').eq('restaurant_id',id).order('name'),supabaseCloud.from('restaurant_captain_sessions').select('*').eq('restaurant_id',id).order('started_at',{ascending:false}).limit(30),supabaseCloud.from('inventory').select('id,name,quantity,unit,reorder_level').eq('restaurant_id',id).order('name').limit(100),supabaseCloud.from('audit_logs').select('id,action,entity_type,created_at').eq('restaurant_id',id).order('created_at',{ascending:false}).limit(30)
 ]);setD({suppliers:q[0].data||[],purchases:q[1].data||[],rewards:q[2].data||[],kiosks:q[3].data||[],kitchens:q[4].data||[],channels:q[5].data||[],recon:q[6].data||[],devices:q[7].data||[],captain:q[8].data||[],inventory:q[9].data||[],audit:q[10].data||[]});setLoading(false)}
 async function add(table,payload){const{error}=await supabaseCloud.from(table).insert({restaurant_id:rid,...payload});setMsg(error?.message||'Saved successfully');if(!error)load()}
 if(loading)return <main className="pp"><div className="load">Loading Anaira Restaurant Suite…</div></main>
 const low=(d.inventory||[]).filter(x=>Number(x.quantity||0)<=Number(x.reorder_level||0)).length
 return <main className="pp"><header><div><small>ANAIRA RESTAURANT SUITE</small><h1>Anaira Restaurant Suite</h1><p>Restaurant operations beyond basic billing. Existing Anaira modules stay intact and this center connects the missing operational workflows.</p></div><div className="headBtns"><a href="/dashboard/restaurant-suite/operations">Operations Hub</a><button onClick={()=>load()}>↻ Refresh</button></div></header>
 <section className="stats"><Stat t="Suppliers" v={d.suppliers?.length||0} i="🛒"/><Stat t="Low stock" v={low} i="⚠️"/><Stat t="Kiosks" v={d.kiosks?.length||0} i="🖥️"/><Stat t="Kitchens" v={d.kitchens?.length||0} i="👨‍🍳"/><Stat t="Channels" v={d.channels?.length||0} i="🌐"/><Stat t="Audit" v={d.audit?.length||0} i="🛡️"/></section>
 <nav>{tabs.map(x=><button className={tab===x[0]?'on':''} key={x[0]} onClick={()=>setTab(x[0])}>{x[1]} {x[2]}</button>)}</nav>{msg&&<div className="msg">{msg}</div>}
 {tab==='purchase'&&<Panel title="Purchase Manager"><p>Supplier, purchase invoice and receiving foundation. Existing inventory remains the source of stock truth.</p><Form fields={[[supplier.name,'Supplier name',v=>setSupplier({...supplier,name:v})],[supplier.phone,'Phone',v=>setSupplier({...supplier,phone:v})],[purchase.invoice_number,'Invoice number',v=>setPurchase({...purchase,invoice_number:v})],[purchase.total,'Total',v=>setPurchase({...purchase,total:v})]]} action={()=>{if(supplier.name)add('restaurant_suppliers',supplier);if(purchase.total)add('restaurant_purchases',{invoice_number:purchase.invoice_number,total:Number(purchase.total),subtotal:Number(purchase.total)})}} text="Save purchase"/><Rows data={d.suppliers.map(x=>[x.name,x.phone||'No phone',x.active===false?'Inactive':'Active'])}/><Rows title="Recent purchases" data={d.purchases.map(x=>[x.invoice_number||'Purchase',x.status,money(x.total)])}/></Panel>}
 {tab==='loyalty'&&<Panel title="CRM & Loyalty"><p>Point rewards use the existing customer wallet, tiers, segments and transaction engine.</p><Form fields={[[reward.name,'Reward name',v=>setReward({...reward,name:v})],[reward.points_cost,'Points',v=>setReward({...reward,points_cost:v})],[reward.reward_value,'Value',v=>setReward({...reward,reward_value:v})]]} action={()=>add('loyalty_rewards',{...reward,points_cost:Number(reward.points_cost),reward_value:Number(reward.reward_value)})} text="Add reward"/><Rows data={d.rewards.map(x=>[x.name,`${x.points_cost} points`,x.active?'Active':'Off'])}/><Links items={['/dashboard/customers','/dashboard/offers']}/></Panel>}
 {tab==='kiosk'&&<Panel title="QR Ordering & Self-Service Kiosk"><p>Register kiosk terminals; the existing QR center remains available for table QR setup.</p><Form fields={[[kiosk.name,'Kiosk name',v=>setKiosk({...kiosk,name:v})],[kiosk.kiosk_code,'Kiosk code',v=>setKiosk({...kiosk,kiosk_code:v})]]} action={()=>add('self_service_kiosks',{...kiosk,active:true})} text="Register kiosk"/><Rows data={d.kiosks.map(x=>[x.name,x.kiosk_code||'No code',x.active?'Active':'Off'])}/><Links items={['/dashboard/qr','/dashboard/restaurant-suite/complete']}/></Panel>}
 {tab==='kitchen'&&<Panel title="Central Kitchen"><p>Central kitchen registry plus existing inventory transfers and recipe automation.</p><Form fields={[[kitchen.name,'Kitchen name',v=>setKitchen({...kitchen,name:v})],[kitchen.code,'Code',v=>setKitchen({...kitchen,code:v})],[kitchen.address,'Address',v=>setKitchen({...kitchen,address:v})]]} action={()=>add('central_kitchens',kitchen)} text="Add kitchen"/><Rows data={d.kitchens.map(x=>[x.name,x.code||'No code',x.active?'Active':'Off'])}/><Links items={['/dashboard/inventory','/dashboard/restaurant-suite/operations']}/></Panel>}
 {tab==='online'&&<Panel title="Online Channels & Reconciliation"><p>Provider configuration and payout reconciliation are stored per restaurant.</p><Form fields={[[channel.channel_code,'Channel code',v=>setChannel({...channel,channel_code:v})],[channel.channel_name,'Channel name',v=>setChannel({...channel,channel_name:v})]]} action={()=>add('online_channels',{...channel,active:false})} text="Save channel"/><Form fields={[[recon.external_order_id,'External order',v=>setRecon({...recon,external_order_id:v})],[recon.gross_amount,'Gross',v=>setRecon({...recon,gross_amount:v})],[recon.commission,'Commission',v=>setRecon({...recon,commission:v})],[recon.payout_amount,'Payout',v=>setRecon({...recon,payout_amount:v})]]} action={()=>add('online_order_reconciliations',{channel_code:channel.channel_code,external_order_id:recon.external_order_id,gross_amount:Number(recon.gross_amount),commission:Number(recon.commission),payout_amount:Number(recon.payout_amount)})} text="Add reconciliation"/><Rows data={d.channels.map(x=>[x.channel_name,x.channel_code,x.active?'Active':'Off'])}/><Rows title="Recent reconciliation" data={d.recon.map(x=>[x.external_order_id||'Order',x.settlement_status,money(x.payout_amount)])}/></Panel>}
 {tab==='calling'&&<Panel title="Wireless Calling"><p>Register table/service calling devices and continue using the existing service-call queue.</p><Form fields={[[device.name,'Device name',v=>setDevice({...device,name:v})],[device.device_code,'Device code',v=>setDevice({...device,device_code:v})],[device.location,'Location',v=>setDevice({...device,location:v})]]} action={()=>add('calling_devices',{...device,active:true})} text="Register device"/><Rows data={d.devices.map(x=>[x.name,x.location||'No location',x.active?'Active':'Off'])}/><Links items={['/dashboard/calling','/dashboard/restaurant-suite/operations']}/></Panel>}
 {tab==='captain'&&<Panel title="Captain / Waiter"><p>Captain sessions are tenant-scoped and ready for mobile/table-side ordering clients.</p><Rows data={d.captain.map(x=>[String(x.id).slice(0,8),x.status,x.offline?'Offline queue':'Online'])}/><Links items={['/order','/dashboard/restaurant-suite/operations']}/></Panel>}
 {tab==='inventory'&&<Panel title="Inventory, Recipe & Food Cost"><p>Existing inventory engine already supports recipes, automatic terminal-sale deduction, stock alerts and food-cost calculation.</p><Rows data={d.inventory.slice(0,40).map(x=>[x.name,`${x.quantity||0} ${x.unit||''}`,Number(x.quantity||0)<=Number(x.reorder_level||0)?'LOW':'OK'])}/><Links items={['/dashboard/inventory','/dashboard/restaurant-suite/operations']}/></Panel>}
 {tab==='reports'&&<Panel title="Reports & Audit / Leakage Control"><p>Cancelled, moved, operational and other actions should remain reviewable. Detailed reporting stays in the existing Reports center.</p><Rows data={d.audit.map(x=>[x.action||'Action',x.entity_type||'Event',new Date(x.created_at).toLocaleString('en-IN')])}/><Links items={['/dashboard/reports','/dashboard/restaurant-suite/operations']}/></Panel>}
 <style jsx global>{styles}</style></main>
}
function Stat({t,v,i}){return <div className="stat"><span>{i}</span><small>{t}</small><b>{v}</b></div>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Form({fields,action,text}){return <div className="form">{fields.map((f,i)=><label key={i}><span>{f[1]}</span><input value={f[0]??''} onChange={e=>f[2](e.target.value)}/></label>)}<button onClick={action}>{text}</button></div>}
function Rows({title,data}){return <div className="rows">{title&&<h3>{title}</h3>}{data.length?data.map((r,i)=><div className="row" key={i}><b>{r[0]}</b><span>{r[1]}</span><em>{r[2]}</em></div>):<div className="empty">No records yet.</div>}</div>}
function Links({items}){return <div className="links">{items.map(x=><a key={x} href={x}>Open {x.replaceAll('/dashboard/','').replaceAll('/',' ')} →</a>)}</div>}
const styles=`.pp{min-height:100vh;padding:28px;max-width:1500px;margin:auto;background:#090e19;color:#f4efe5}.pp header{display:flex;justify-content:space-between;gap:20px;padding:28px;border:1px solid rgba(231,174,57,.25);border-radius:24px;background:linear-gradient(135deg,rgba(231,174,57,.09),rgba(255,255,255,.02))}.pp header small{color:#e7ae39;font-weight:900;letter-spacing:.15em}.pp h1{font-size:clamp(28px,4vw,46px);margin:8px 0}.pp header p{color:#aab4c7;max-width:820px}.headBtns{display:flex;gap:10px;align-items:flex-start}.headBtns a,.headBtns button,.pp nav button,.form button,.links a{border:1px solid rgba(231,174,57,.3);background:#121a2a;color:#f4efe5;border-radius:12px;padding:11px 15px;font-weight:800;text-decoration:none;cursor:pointer}.headBtns button,.pp nav button.on,.form button:hover,.links a:hover{background:#e7ae39;color:#111}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:18px 0}.stat{padding:16px;background:#101828;border:1px solid rgba(255,255,255,.08);border-radius:18px}.stat span{font-size:21px}.stat small{display:block;color:#9ca8bb;margin-top:7px}.stat b{font-size:25px}.pp nav{display:flex;gap:8px;overflow:auto;padding:6px 0 16px}.pp nav button{white-space:nowrap}.panel{padding:22px;border:1px solid rgba(255,255,255,.09);border-radius:22px;background:#0f1727}.panel h2{margin:0 0 14px}.panel>p{color:#aab4c7}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.form label{display:flex;flex-direction:column;gap:7px}.form label span{font-size:12px;color:#9ca8bb;font-weight:800}.form input{padding:11px;border-radius:11px;border:1px solid rgba(255,255,255,.12);background:#090f1b;color:#f4efe5}.form button{align-self:end}.rows{margin-top:18px}.rows h3{margin-bottom:10px}.row{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;padding:12px 0;border-top:1px solid rgba(255,255,255,.07)}.row span{color:#aab4c7}.row em{font-style:normal;color:#e7ae39;font-weight:800}.empty{padding:18px;border:1px dashed rgba(255,255,255,.15);color:#8e9aae;border-radius:14px}.links{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.msg{position:fixed;right:20px;bottom:20px;padding:14px 18px;border-radius:14px;background:#172033;border:1px solid #e7ae39;z-index:50}.load{text-align:center;padding:60px;color:#aab4c7}@media(max-width:1100px){.stats{grid-template-columns:repeat(3,1fr)}.form{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.pp{padding:14px}.pp header{flex-direction:column}.headBtns>*{flex:1}.stats{grid-template-columns:repeat(2,1fr)}.form{grid-template-columns:1fr}.row{grid-template-columns:1fr}.panel{padding:16px}}`
