import {NextResponse} from "next/server"
import {supabaseCloudAdmin} from "@/lib/supabaseCloudServer"
import {requireApiUser} from "@/lib/serverAuth"
import {requireSuperAdmin} from "@/lib/serverStaffPermissions"
export const runtime="nodejs"
async function sa(req){const u=await requireApiUser(req);await requireSuperAdmin(u);return u}
export async function GET(req){try{await sa(req);const {data,error}=await supabaseCloudAdmin.from("platform_marketing_posts").select("*").order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({success:true,posts:data||[]})}catch(e){return NextResponse.json({success:false,error:e.message},{status:403})}}
export async function POST(req){try{const u=await sa(req),b=await req.json();const platform=String(b.platform||"").toLowerCase();if(!["facebook","instagram","whatsapp"].includes(platform))throw new Error("Unsupported platform");const {data,error}=await supabaseCloudAdmin.from("platform_marketing_posts").insert({platform,content_type:b.content_type||"text",caption:String(b.caption||""),media_urls:Array.isArray(b.media_urls)?b.media_urls:[],status:b.scheduled_at?"scheduled":"draft",scheduled_at:b.scheduled_at||null,created_by:u.id,campaign_id:b.campaign_id||null,template_name:b.template_name||null,template_language:b.template_language||null,metadata:b.metadata&&typeof b.metadata==="object"?b.metadata:{}}).select("*").single();if(error)throw error;return NextResponse.json({success:true,post:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}

export async function PATCH(req){try{await sa(req);const b=await req.json();if(!b.id)throw new Error("Post id is required");const patch={};for(const k of ["published_at","external_id","caption","media_urls","scheduled_at","template_name","template_language","campaign_id","metadata"]){if(b[k]!==undefined)patch[k]=b[k]} if(b.status!==undefined){const status=String(b.status); if(!["draft","scheduled","cancelled"].includes(status)) throw new Error("Published status is system-controlled"); patch.status=status}const {data,error}=await supabaseCloudAdmin.from("platform_marketing_posts").update(patch).eq("id",b.id).select("*").single();if(error)throw error;return NextResponse.json({success:true,post:data})}catch(e){return NextResponse.json({success:false,error:e.message},{status:400})}}
