"use client"
import Link from "next/link"
import PublicMarketingChrome from "@/components/PublicMarketingChrome"
const groups=[
 ["01","Core Operations","Run daily restaurant work from one connected workspace.",["Restaurant POS","Orders & Tables","Billing & Invoices","Reservations","Staff workflows","Daily reports"]],
 ["02","Digital Ordering","Give guests a faster way to browse and order.",["Branded QR Menu","Table QR Ordering","Room / guest ordering","Menu variants","Offers & combos","Order status"]],
 ["03","Kitchen & Delivery","Keep fulfilment moving from order to completion.",["Kitchen Display / KDS","Live preparation states","Delivery management","Rider assignments","Delivery events","Settlement & slips"]],
 ["04","Customers & Growth","Turn restaurant activity into repeat business.",["Customer data","Marketing campaigns","Facebook & Instagram","WhatsApp workflows","Audience management","Lead capture"]],
 ["05","Analytics & Control","See what is happening and make better decisions.",["Sales analytics","Product performance","Operational reports","Campaign attribution","Plugin controls","Restaurant-wise isolation"]],
 ["06","Platform Foundation","Built as a modular SaaS product rather than a collection of disconnected tools.",["Cloud-first architecture","Supabase backend","Role-based access","Plugin architecture","Responsive web experience","Desktop / mobile pathways"]]
]
export default function Features(){return <PublicMarketingChrome><main><style jsx>{`.hero{padding:82px 0 55px;background:radial-gradient(circle at 75% 10%,rgba(245,183,46,.14),transparent 34%)}.hero h1{font-size:clamp(44px,6vw,70px);line-height:.96;letter-spacing:-.06em;margin:14px 0}.gold{color:var(--gold)}.hero p{max-width:730px;color:var(--muted);line-height:1.8;font-size:16px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}.btn{padding:13px 18px;border-radius:11px;text-decoration:none;font-size:12px;font-weight:850}.primary{background:linear-gradient(135deg,var(--gold),var(--gold2));color:#17110a}.secondary{border:1px solid var(--line);color:#fff;background:rgba(255,255,255,.04)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;padding:20px 0 80px}.card{padding:25px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,#0c1726,#07101b)}.num{color:var(--gold);font-size:10px;font-weight:900;letter-spacing:.12em}.card h2{font-size:20px;margin:12px 0 7px}.card p{color:var(--muted);font-size:12px;line-height:1.7;min-height:42px}.list{display:grid;gap:7px;margin-top:18px}.item{padding:9px 0;border-top:1px solid rgba(255,255,255,.07);color:#d8e1eb;font-size:11px}.item:before{content:'✓';color:var(--green);font-weight:900;margin-right:8px}.bottom{padding:65px 0;text-align:center;border-top:1px solid var(--line);background:radial-gradient(circle at 50% 0,rgba(56,211,159,.09),transparent 38%)}.bottom h2{font-size:clamp(32px,5vw,48px);margin:10px 0}.bottom p{color:var(--muted);max-width:650px;margin:auto;line-height:1.75}.bottom .actions{justify-content:center}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.grid{grid-template-columns:1fr}.hero{padding-top:65px}}
`}</style><section className="hero"><div className="amContainer"><div style={{color:'var(--gold)',fontSize:11,fontWeight:850,letterSpacing:'.14em'}}>ANAIRA POS FEATURES</div><h1>Built around the way a <span className="gold">restaurant actually works.</span></h1><p>From the first guest interaction to the kitchen, bill, delivery, customer relationship and marketing campaign — Anaira connects the workflow without turning your team into software experts.</p><div className="actions"><Link className="btn primary" href="/demo">Explore the Demo →</Link><Link className="btn secondary" href="/login">Existing Customer · Sign In</Link></div></div></section><section className="amContainer"><div className="grid">{groups.map(([n,t,d,items])=><article className="card" key={n}><div className="num">{n}</div><h2>{t}</h2><p>{d}</p><div className="list">{items.map(x=><div className="item" key={x}>{x}</div>)}</div></article>)}</div></section><section className="bottom"><div className="amContainer"><div style={{color:'var(--gold)',fontSize:11,fontWeight:850,letterSpacing:'.13em'}}>SEE IT IN ACTION</div><h2>One system. One workflow.</h2><p>Explore the interactive product presentation, compare the public plans or speak directly with the Anaira team about your restaurant.</p><div className="actions"><Link className="btn primary" href="/demo">View Product Demo →</Link><Link className="btn secondary" href="/contact">Talk to Anaira →</Link></div></div></section></main></PublicMarketingChrome>}
